### ISSUE TITLE
Default routing breaks in Chrome

### ISSUE THREAD

**Issue by dethe** [participedia/frontend#101]
Not sure if anyone else is seeing this or if it is due to my browser configuration, but when I start the frontend app locally, it opens in Chrome (not in my default browser) with the URL `http://localhost:3000/` which then redirects to `http://localhost:3000/en/` which gives a blank page with the console message `Warning: [react-router] Location "/en/" did not match any routes`.

Opening `http://localhost:3000` in Firefox redirects to `http://localhost:3000/en-US/` which works fine. If anyone else can reproduce this, I can see two potential fixes: either change the routing to ensure it routes to the full language+region ISO name (i.e., "en-US" vs "en") or make sure the routing can cope with the ISO language only (i.e., make "/en/" work).

Not sure why this would only happen in Chrome though, so if no-one else is seeing it I'm inclined to blame my local setup and move on. Manually changing the URL in Chrome to `/en-US` works.

**Comment by davidascher** [comment]
I'm not seeing this problem in Chrome, so that's interesting.

I'm not convinced the routing system that I'm using is optimal. It is based
on what Mozilla sites have done, and I think for an academic site having
language-specific URLs which point to specific translations is probably the
right thing, but it may be worth reviewing at some point.

I would suggest we review this issue when we do a localization sprint.

**Comment by dethe** [comment]
The culprit seems to be this code in `frontend/src/routes.js` lines 27-35:

```
  // support for HTML 5.1 "navigator.languages"
  if (Array.isArray(nav.languages)) {
    for (i = 0; i < nav.languages.length; i++) {
      language = nav.languages[i]
      if (language && language.length) {
        return language
      }
    }
  }
```
In Chrome my `navigator.languages` is `["en", "en-US"]` and we return the first one we find.  In Firefox my `navigator.languages` is `["en-US", "en" "pt-BR"]` (I think that last one is in there from testing I was doing way back on Mozilla Marketplace and explains why some websites seem to think I want Portuguese).

In both browsers my `navigator.language` is `"en-US"`, so maybe we should check that before iterating through `languages`?

**Comment by davidascher** [comment]
I stole that code from some mofo sites. I would ask someone with more i18n
experience on dom variables, as who knows what the world is like.

**Comment by davidascher** [comment]
Are you still seeing this @dethe ?

**Comment by davidascher** [comment]
fixed when I got rid of locales in URLs
