### ISSUE TITLE
Revise search results display

### ISSUE THREAD

**Issue by samjiangweb** [participedia/frontend#140]
Hey Andrea, I discussed this with Amber: we need to revise how the search results are being displayed on the homepage and I'll need your help to get this working: 

- Remove .result-category > .category-title from displaying
- Show results for ALL + Most Recent in one list / grid 
- Should be organized by most recent, with Cases, Methods, Organizations, etc.. mixed 
- On filter of 'Cases', list shows only cases, with an intro paragraph of what cases are beneath the horizontal filter bar & repeat for Methods, Organizations, News. 

Let me know if you've questions :) Thanks!

**Comment by davidascher** [comment]
Q: ALL will show only the "last 30" or whatever.  So it's OK if those 30 are all cases for example?

**Comment by samjiangweb** [comment]
Hmm, that's a good point. We'll need to check with Amber on that. If Cases rep the majority of updated and new content, this might not be such a good idea.

**Comment by davidascher** [comment]
the point is we can't know what will be recent. it's not just about cases, it could be just orgs. What about news, how do we want to treat them?  they 'feel' different.

**Comment by samjiangweb** [comment]
If I'm filtering by cases - it will present a max of 30 cases - we're paginating after 30 right?

**Comment by davidascher** [comment]
currently, yes.  Easily adjusted.

**Comment by davidascher** [comment]
I'm going to close this and encourage you (@samjiangweb) to file many small issues for remaining work.
