### ISSUE TITLE
Quick Submit not sending all information

### ISSUE THREAD

**Issue by dethe** [participedia/frontend#172]
Only `location`, `summary`, `title`, and `vidURL` are being submitted, not sending data for `image` or `related cases`

**Comment by dethe** [comment]
* [ ] Related cases sending title (which may not be unique) rather than case_id
* [ ] Lead image still not being submitted
* [ ] Method quick submit not submitting at all
* [ ] Organization quick submit not submitting at all

**Comment by davidascher** [comment]
finished in #195
