### ISSUE TITLE
HOMEPAGE - intro dialog

### ISSUE THREAD

**Issue by samjiangweb** [participedia/frontend#189]
Let's add a new content block on the homepage below the header and above the map - Attached is a sample design. Note: the message should read, "Participedia is a global community sharing knowledge and stories about public participation."

Could have (a nice feature):
A text link + symbol to dismiss the message (Okay, got it)
Cookie that remembers when users have dismissed this message - and will not show again.  

![sample-mainpage](https://cloud.githubusercontent.com/assets/25598431/24779793/644fa624-1ae7-11e7-91b1-899ab395c575.jpg)

**Comment by andreadelrio** [comment]
@samjianga hey Sam can you provide the asset for the information bubble please?

**Comment by andreadelrio** [comment]
Done in #194

**Comment by davidascher** [comment]
I have to say this treatment makes it feel like one of those hyper annoying cookie warnings, which I don't think is the spirit of the note.  Am I alone in having that reaction? @samjianga @jesicarson @dethe @andreadelrio

**Comment by davidascher** [comment]
I'd also say the X mark as implemented looks like an X, not like a close widget.  I'd make it bolder, and use a more iconic form.  Preferably https://material.io/icons/#ic_close as it's a Material icon which we use elsewhere.

**Comment by andreadelrio** [comment]
@davidascher It reminds me a lot of the EU cookie warning. I would find a place to (permanently and more subtly) display Participedia's one liner. Also, I just added a nicer "x" on the `welcome` branch.

**Comment by samjiangweb** [comment]
Yeah, you're right @davidascher - I'll address the visual design a bit.. to make it feel less.. cookie. There may be some implications with updates to maps that we're planning to look at. Either way, it helps give people context around what this site is all about.

**Comment by davidascher** [comment]
I would also use the opportunity to tell people to visit the About page or somewhere new visitors can read more about PP.

**Comment by samjiangweb** [comment]
ah, right - I'll take this as feedback to make the callout on this a bit more prominent.

**Comment by davidascher** [comment]
oh, wow, i totally missed it.  i'm blind sometimes. 😨

**Comment by samjiangweb** [comment]
nope! not your fault - it's a visual design UX problem ;)

**Comment by jesicarson** [comment]
Post-meeting update: 
@samjiangweb is working on an updated design for this which will look less like a cookie warning visually. On dismissal, the message will collapse back up but reveal some way to bring it back down (maybe an icon next to the logo). Text would be the first paragraph of the about page or similar, to give more about the project than the one liner currently does. Sam, I'll get you this copy!
