### ISSUE TITLE
Search Results - Add in "type" label in search results

### ISSUE THREAD

**Issue by samjiangweb** [participedia/frontend#190]
Let's add the type label (case, method, news) back into the search results. 

This is so that visitors can tell what type of content they're reviewing at a glance of the results - especially when filtering by "All" 

![screen shot 2017-04-06 at 4 43 02 pm](https://cloud.githubusercontent.com/assets/25598431/24779890/22086dcc-1ae8-11e7-962c-57158654c241.png)

**Comment by davidascher** [comment]
done.
