### ISSUE TITLE
SEARCH - Sort by date - both ascending and descending 

### ISSUE THREAD

**Issue by samjiangweb** [participedia/frontend#191]
Currently, the planned functionality of the "date" sorting is only be most recent, - while this should be the default, we should also provide an option to sort by earliest. Haven't thought too far into how this should be displayed - there are a few options - so feel free to check in with me (Sam) about this!

**Comment by samjiangweb** [comment]
Hey @davidascher @andreadelrio - I've attached an image to show the revised sorting box in the sidebar. First, we want to give it a title, "Sort Results by" 

Second, let's change the language from "Most recent" and "Alphabetical" to "Date Published" and "Title (A–Z)" respectively. 

These links should re-sort on click.. as default click - sort by most recent, or "A" first. On second click, toggle to sort by earliest, or by "Z" first. 

The arrows should also give users an indication of sort order - down arrow active - correlating with "most recent" and "A first", up arrow active - correlating with "earliest" and "Z first" 

Also, changing 'alphabetical' to 'title (a-z)' gives a more clear indication of what we're actually sorting. 

Let me know if you have questions, thoughts, or suggestions on this!
![screen shot 2017-04-11 at 7 12 59 pm](https://cloud.githubusercontent.com/assets/25598431/24938579/f2c7d44a-1eec-11e7-8648-9b4f87775e35.png)

**Comment by davidascher** [comment]
Looks good.  Confirming we want to sort by Date Published, not Date Last Edited?

When sorting descending alphabetically, do we want to update the text to say Title (Z-A)?

I will say that Date published 'up' is a bit opaque to me. Do you agree? How about something like

* Date Published [no selection]
* Most recently published [down]
* Least recently published [up]

?

**Comment by davidascher** [comment]
I'm not satisfied w/ my suggestion.
