### ISSUE TITLE
Let's make sure mobile views are polished

### ISSUE THREAD

**Issue by davidascher** [participedia/frontend#197]
I see a few problems:

<img width="347" alt="screenshot 2017-04-08 11 36 44" src="https://cloud.githubusercontent.com/assets/51278/24831518/b695de80-1c4f-11e7-8c73-fa9b4d7cfa0d.png">

The + icon needs a better place to live (note @samjiangweb  -- this is why the FAB button is a popular widget in mobile views)

<img width="359" alt="screenshot 2017-04-08 11 36 34" src="https://cloud.githubusercontent.com/assets/51278/24831519/b8619f1a-1c4f-11e7-830e-4f4bad00d868.png">

Something about this view is stretching the top bar wider than the display port, probably the image?  @andreadelrio any ideas?

**Comment by andreadelrio** [comment]
@davidascher 
```
<div
  className="case-html"
  dangerouslySetInnerHTML={{ __html: caseObject.body }}
/>
```
this is breaking the mobile view, will add one CSS line to fix it.

**Comment by samjiangweb** [comment]
I'll take a look at the mobile placement of the add/create button -

**Comment by davidascher** [comment]
@andreadelrio I've made some changes to the CSS to shift things in both the main search results view and the profile view, and now the mobile view is worse =).

For now, can we bring back the FAB + button for mobile views, and get rid of the + in the header?

**Comment by andreadelrio** [comment]
@davidascher ok just sent a PR #303

**Comment by andreadelrio** [comment]
As a general rule of thumb, let's not modify the horizontal padding (or manually set the width) of Bootstrap's containers, rows and columns. Doing so it's dangerous because it can break the grid system.

**Comment by davidascher** [comment]
Roger.
