### ISSUE TITLE
Design decision: what to display in the case of missing metadata?

### ISSUE THREAD

**Issue by davidascher** [participedia/frontend#200]
Hey @jesicarson and @samjiangweb:

When looking at a case detail page for example, there will be lots of fields (tags, related cases, etc.) for which any one case is likely to have no data.  Should we show this absence of data ("Related cases: None") or just not show the heading at all?  

From a readers PoV I would say not showing the heading for bits of data that we don't have about a particular case makes for easier reading, and naturally draws the eye to the bits we have (in the screen grab below, the only thing we _know_ is the `Specific Topic`. We obviously would show all possible fields in the 'edit' view.

What say you?

<img width="256" alt="screenshot 2017-04-08 13 09 06" src="https://cloud.githubusercontent.com/assets/51278/24832071/94a32cda-1c5c-11e7-9f74-bda65586bc87.png">

**Comment by samjiangweb** [comment]
Hey @davidascher  - I agree - there's a lot of repetition if these things aren't specified. My vote is we hide the fields with no metadata specified as well.

**Comment by davidascher** [comment]
coolio

**Comment by davidascher** [comment]
decision made, closing.
