### ISSUE TITLE
Close menu when user clicks on an item

### ISSUE THREAD

**Issue by andreadelrio** [participedia/frontend#21]
Right now the user has to manually close the menu after they click on a menu item.

**Comment by davidascher** [comment]
I am not seeing this anymore. I think it was fixed yesterday or monday.  Can you pull and check again?

**Comment by andreadelrio** [comment]
@davidascher yes, you're right! will make sure to pull latest changes before creating a new issue next time.

**Comment by davidascher** [comment]
Not a problem!  Better too many bugs filed than too few.
