### ISSUE TITLE
Clean up icons on cases/methods/etc.

### ISSUE THREAD

**Issue by davidascher** [participedia/frontend#217]
![image](https://cloud.githubusercontent.com/assets/51278/24938738/e2f93f9e-1eed-11e7-8cd8-9b3c0d31324a.png)

**Comment by davidascher** [comment]
For that matter, I know what the share icon can do on android at least, but I don't know what it should do on desktop.

**Comment by samjiangweb** [comment]
I'm actually not certain what those do. Let me look into it.

**Comment by samjiangweb** [comment]
lol, exhibit A: https://en.wikipedia.org/wiki/Mystery_meat_navigation - creators aren't even sure what this is. @jesicarson - I had a look through the original mockups and didn't find much on that. Can you weigh in?

**Comment by jesicarson** [comment]
I dont think we need it - settings can be accessed via the user profile. 

There was also the bookmark icon there before, which is missing. Can we bring that back? We also want to be able to bookmark from a list of search results.

**Comment by davidascher** [comment]
Bookmark icon currently only shows while logged in but I'll bring it back and force login when clicked.

**Comment by davidascher** [comment]
- [ ] remove red settings icon
- [ ] bring back bookmark icon even when not logged in.
