### ISSUE TITLE
Search: UI scattered

### ISSUE THREAD

**Issue by dethe** [participedia/frontend#223]
For search we have facets (like country and tag), filters (like case vs. method), and free-form full text query. As a user, it is confusing to me a) which ones persist after I set them, b) how they interact, and c) how to clear them. I think we should have one place where we show all parts of the search in one place that can be updated or cleared (probably the search field itself). We might want to make the object type filter into a facet for consistency (i.e.: `in:cases` vs. `objType=Cases`, at least when displayed to the user).

This way skilled users can actually type in the (possibly complex) query they want, combining multiple facets if desired, and clicking on searchable items is basically just a shortcut for typing in that faceted search, demonstrating how to query.

**Comment by samjiangweb** [comment]
@dethe  agreed - for the filters case/methods/organizations - we will be giving those links an active state - it would also be nice to show a brief description that summarizes what a case or method is - before listing the content. 

As far as search terms go through the search field - check out  https://www.edmonton.ca/ and do a search for 'books' or something. A blurb of text before the results that say "Search results for *books*" and then tell's us we're seeing results 1-10 (30) of 12345 would be helpful :)

**Comment by davidascher** [comment]
Thinking about this, trying to figure out what is search, what is navigation, and what is UI state which need not be in the URL.

Here's where my mind is at for how to encode search results in the URL first:

- `/`: show everything, show first page of results
- `/?page=4`: show page 4 of all results
- `/?sort=alphabetical&page=4`: show page 4 of all results, sorted alphabetically
- `/?sort=inversealphabetical&page=4`: show page 4 of all results, sorted alphabetically, backwards (as a result of clicking on a sort order arrow)
- `/cases`: show all cases, show first page of results
- `/cases?page=4`: show all cases, show fourth page of results

(obviously similarly for `methods` and `organizations`)

This means that `/`, `/cases`, `/methods` and `/organizations` are "promoted" navigational concepts.

Then:

- `/?q=Paris`: show everything that mentions paris
- `/?location:country=France`: show everything that has `France` as a value in field `location:country`
- similarly for every other field, using combinations as well:
  - `/cases?location:country=France&in_progress=True`: in progress cases in France.

Some things do not show up in the URL or the UI, but are persistent, at this point only whether to show list view or icon view.

Here's the big question: what do we show in the search bar?  I like Edmonton's take to basically make it an approximate, critically _simple_ term.  I don't think we need/want to teach people about the search syntax.  The search URLs may get complex through simple navigation, but what's most critical about the search box is that it is not scary.

What information do we want to show for example if someone does a search like: - `/cases?location:country=France&in_progress=True&page=4` ?  I suspect, we just show `France`.

**Comment by dethe** [comment]
One of the key reasons (to me, at least) for showing things in the search bar is not as a teaching aid for search syntax, but to show what search/sort/filtering is being applied *right now* and to give a way to clear any or all of that. So I don't mind keeping the search bar simple, as long as we have ways of doing those two things (and I don't count the URL which is still Deep Magic for a lot of people).

**Comment by davidascher** [comment]
Indeed.  So, page # would show up in a pagination widget.  Sort order would show up with the arrow widgets.  Anything else will need a "chip" of some kind with an x next to it:   

  ( in_progress: [x] )

That what you mean?

**Comment by dethe** [comment]
Yes, and preferably all of those would be close enough together in the UI that a person could tell at a glance "where they are".

**Comment by davidascher** [comment]
@samjiangweb do you agree? If so I can start to work on the logic side while you think of the UI bits.

**Comment by davidascher** [comment]
Question: what happens if you change the search term and hit enter?  My proposal is that it resets: field-level faceting and page #; it preserves the "kind" categorization and sort order.

**Comment by jesicarson** [comment]
@samjianga perhaps the comment I just left on issue #192 should have gone here: 
... "there was mention in the meeting today about the need for design related to options for selecting previous / next / first page / last page on search results" which to me sounds like we're going ahead with David's suggestions above that deal with the issue of helping users know where they are and be able to clear search results, as Dethe pointed out. Thanks.

**Comment by davidascher** [comment]
I think this has been covered in either implementation or other bugs.
