### ISSUE TITLE
Make both home page and case detail page pull the real images

### ISSUE THREAD

**Issue by davidascher** [participedia/frontend#24]
Currently, the home page uses grey placeholders for the images, and the detailed pages uses fake images.  Let's use the real images that we have.

Background:

The case/method/etc. records have fields which include filenames (e.g. "Jp00123.JPG").  The images that these correspond to have been dumped in the s3 bucket called `assets.participedia.xyz`, meaning that they're available at http://assets.participedia.xyz.s3.amazonaws.com/

First step is to in each both the search results view and the case detail view, extract the relevant filenames, and create the right URL to those assets in the rendering.

**Comment by andreadelrio** [comment]
It looks like there might have been a problem when transferring some of the images.
Some cases could be related to spaces in the original image filename but others are not showing the existing lead_image for no particular reason, as far as I can tell.

Examples:

Case id 468 
http://participedia.net/sites/default/files/styles/medium/public/agenda21%20.jpg
http://assets.participedia.xyz.s3.amazonaws.com/agenda21%20.jpg [not working]


Case id 485
http://participedia.net/sites/default/files/styles/medium/public/800px-2007_07_Belgium_Brussels_06_%28cropped%29-1.jpg
http://assets.participedia.xyz.s3.amazonaws.com/800px-2007_07_Belgium_Brussels_06_%28cropped%29-1.jpg [not working]

**Comment by davidascher** [comment]
Ah that's annoying. I'll check what script I used to pull the images.

**Comment by andreadelrio** [comment]
Ran into another case:

http://www.participedia.net/sites/default/files/styles/medium/public/eu_logo.jpg
http://assets.participedia.xyz.s3.amazonaws.com/eu_logo.jpg [not working]

**Comment by andreadelrio** [comment]
@davidascher Another case
http://participedia.net/sites/default/files/styles/medium/public/e-delib_circles_grc.jpg
http://assets.participedia.xyz.s3.amazonaws.com/e-delib_circles_grc.jpg [not working]
