### ISSUE TITLE
Something is making the top level frame too wide

### ISSUE THREAD

**Issue by davidascher** [participedia/frontend#270]
by only a few pixels, but it's making the zoom controls be half-hidden.

<img width="1038" alt="screenshot 2017-04-24 08 48 38" src="https://cloud.githubusercontent.com/assets/51278/25345858/e614e2a0-28ca-11e7-8ee4-c02d0db5be95.png">

**Comment by andreadelrio** [comment]
@davidascher at what resolution is that happening? I can't seem to reproduce. I've tried 1440 x 900 and 1280 x 800.

**Comment by davidascher** [comment]
Weird.  For me it's at all widths that show the map, for both firefox and chrome.
