### ISSUE TITLE
Create New User Account with Gmail - Glitch

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#272]
@davidascher 
Just signed up/ logged in for the first time with gmail to the xyz site and was redirected (after clicking "allow" to gmail access) to a blank screen saying "no data yet". Is this a known issue?
![screen shot 2017-04-25 at 9 25 20 am](https://cloud.githubusercontent.com/assets/13560530/25396489/9ad9d4f6-2999-11e7-9680-8983ee8a3645.png)

**Comment by davidascher** [comment]
Nope, that's new to me. Thanks for filing.

**Comment by jesicarson** [comment]
Logging out and back in worked. It recognized my last login with gmail, and redirected to the home page.

**Comment by davidascher** [comment]
Thanks.  Still a serious bug worth fixing soon, but glad you're in.  BTW, I made you a curator so you should be abel to see the Featured toggle (but it doesn't do anything yet).

**Comment by dethe** [comment]
Cannot reproduce, logging in via gmail seems to work fine. Please re-open if it is seen again.
