### ISSUE TITLE
MAP: blurry text in popups on non-retina screens

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#273]
Should remain at current level of zoom when a pin is clicked. 

Before click:
![screen shot 2017-04-25 at 9 40 46 am](https://cloud.githubusercontent.com/assets/13560530/25396940/51489e60-299b-11e7-9290-358d31db1dda.png)

After click:
![screen shot 2017-04-25 at 9 40 53 am](https://cloud.githubusercontent.com/assets/13560530/25396952/5c7314e6-299b-11e7-9ba2-d75ca363fc62.png)

**Comment by davidascher** [comment]
What's the blurry issue?  

It's easy to not zoom when clicking, but I wonder -- what do you think instead of zooming out when people click on a non-pin?

**Comment by jesicarson** [comment]
Right now, nothing happens on a single click outside a pin (other than click and drag to move). Would single click to zoom out be super weird?

Blurry - 
Can you see it in the screenshot? Maybe it's just my screen. The map still looks a little jagged too.

**Comment by davidascher** [comment]
Can you check your screen isn't zoomed? (cmd-0)

There should be no blurriness, although when you zoom the map will need to redraw and get more data, so that may be blurry until that finishes.

I can undo the zoom on click-pin.

**Comment by jesicarson** [comment]
I'm not zoomed, I did command-0.

**Comment by jesicarson** [comment]
You can have a look at my screen next time we meet maybe?

**Comment by davidascher** [comment]
blurriness: https://github.com/mapbox/mapbox-gl-js/issues/3249 

Andrea can you look at this?

**Comment by andreadelrio** [comment]
@davidascher will do
