### ISSUE TITLE
Quick Submit fields for Cases

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#280]
- Name of case (rather than “title”), Explanatory text: “Please give this public participation project or event a descriptive title in 15 words or less. For example, “Brazilian Dialogue on Diversity" or "New York City Public Issues Forum."
- Short description (limited word count - tweet length?)
- Location (start typing & select from dropdown)
- Start date
- End date
- General issues (use existing list of general issues from .net, select one or multiple), explanatory text: “Please indicate the issue or issues addressed. These categories are general and inclusive.”
- Intended purpose (Use existing list of purposes from .net, select one or multiple), explanatory text: “Please feel free to indicate more than one intended purpose where appropriate.”
- Links (reference urls - no limit to number) 
- Media (photo / video - no limit to number)

**Comment by dethe** [comment]
@andreadelrio Is there anything here which is not implemented yet? If so, let's finish it, otherwise we can just close it.

**Comment by dethe** [comment]
@jesicarson What seems to be missing here are `short description` which could overlap with the `description` in the longer form in potentially complex ways or could be a brand new field we add to the data model, and `intended purpose` which is also something missing from our data model. Do we need these changes for "before user testing"?

**Comment by jesicarson** [comment]
@dethe I think this issue is dated and theres a more recent issue for the data forms as per Pat... I don't think we should refer to this at all.
