### ISSUE TITLE
Copy for About, Teaching & Research Pages

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#281]
I will put copy here for @andreadelrio to add to these pages.

**Comment by jesicarson** [comment]
Hi @andreadelrio,

Ok, so this is taking a liiiitle longer than I thought, however you can reference the mockup below to see some of the adjustments to the text area that will be needed for about/ teaching/ research (you can ignore the header and footer changes, as those I will work out with Sam tomorrow, they are just visual placeholders for this mockup). ai file and mockup jpg are both in [this mockup folder](https://drive.google.com/drive/folders/0B5j_dGoSFCLJWFhCNGMwalVFT28?usp=sharing) in the D&T drive.

I'm also working on the actual text for you in [this copy deck](https://docs.google.com/document/d/1eUVXSBHN_QqR5O_MCNHpiplAAr51K3EM5yOo8w05I5k/edit?usp=sharing) in google docs, you can jump down to the about section bookmark to see the progress. Feel free to take what's there, the rest I will fill in as I go. About section is almost done, and will hop on to teaching and research tomorrow. 

If there's anything about this workflow that could be better, feel free to let me know. Cheers!

![april 27-about page mockup](https://cloud.githubusercontent.com/assets/13560530/25509715/d63d97bc-2b6f-11e7-90f2-a10195cf6238.jpg)

**Comment by andreadelrio** [comment]
@jesicarson got it!

**Comment by andreadelrio** [comment]
@jesicarson just wanted to double check, the mockup is only for layout purposes but the actual content I get from the Google Doc right?

**Comment by jesicarson** [comment]
@andreadelrio yes thats right, although the doc is not totally complete yet. I'll let you know as that progresses.

**Comment by jesicarson** [comment]
@andreadelrio about, teaching and research copy is up to date in the copy deck. Let me know if you need anything else for these or if anything is unclear. Thanks!

**Comment by jesicarson** [comment]
@andreadelrio Can you use the footer design from this mockup on the live site? So include the logo and one liner positioning shown above. Thanks!

**Comment by andreadelrio** [comment]
@jesicarson will do. Also, I left some comments/questions for you in the Google Doc.

**Comment by jesicarson** [comment]
Thanks @andreadelrio. Replied in the doc!

**Comment by andreadelrio** [comment]
Covered in #348
