### ISSUE TITLE
MAP: Use highlight color for markers that correspond to the current search 

### ISSUE THREAD

**Issue by davidascher** [participedia/frontend#288]
(part of #260, putting here for narrower scope).

We want to highlight those markers on the map which correspond to the current search.

This will require factoring out the search process so that there's a single point of search aggregation (currently in `SearchResults`), which spawns two searches: one, paginated, for the search results, which returns everything required for displaying those, and one, not paginated, which returns everything the map needs.

**Comment by jesicarson** [comment]
I will do mockups of the following options:

OPTION 1:
Cases - red
Methods - yellow
Orgs - blue
Other - grey

OPTION 2:
results - black
other - grey

OPTION 3:
results - red
other - black

**Comment by jesicarson** [comment]
See #584 for colour mockups
