### ISSUE TITLE
Allow users to edit their profile

### ISSUE THREAD

**Issue by davidascher** [participedia/frontend#30]
- [ ] Write API /user POST endpoint & doc
- [x] Figure out which data lives in Auth0 at rest (likely name, avatar, etc.) or in DynamoDB (affiliation, bookmarks, etc.)
- [ ] implement API endpoint to dispatch writes to the right backend
- [ ] implement front-end editing flow, including validation & error checking.
- [ ] tests for all of the above

**Comment by davidascher** [comment]
Given that you've already dug into the Auth0 part of this, do you want to take the rest of profile editing @andreadelrio?

**Comment by andreadelrio** [comment]
@david so these are the fields we have for a user edit profile right now:

1. Location

2. Organization

- Organization name (with AutoComplete)
- Department
- Title
- Website

3. Biography

Which of this would be want in Auth0 and which in DynamoDB? I think `location` and `biography` could go to Auth0.

**Comment by davidascher** [comment]
Yeah I was starting work on that yesterday and I was thinking that it would
be a lot more work to have two user tables than one in auth0. Given that
dynamodb doesn't let us do joins across tables anyway, I don't know if
there's a reason to split the data across the two dbs. Am I forgetting
something?

We'd still need to manage IDs that are participedia specific but that feels
like metadata we can just attach to the user in auth0.

I'm going to look into that today but comments welcome from you or dethe.

**Comment by andreadelrio** [comment]
Sounds like trying to stick with Auth0 only is better. Also, when the user logs in we could generate our own ID for them and save it as `user_metadata` in Auth0 and then we could just look them up in Auth0 using that new ID. (This relates to the proxy issue https://github.com/participedia/api/issues/6)

**Comment by davidascher** [comment]
Yup my thinking exactly

**Comment by dethe** [comment]
Given that profile editing is working for me, I'm closing this.
