### ISSUE TITLE
Handle results from new search API

### ISSUE THREAD

**Issue by dethe** [participedia/frontend#305]
The new (faster) search returns results differently.

OLD API:

```
{"results": [ 
  { "type": "case", "hits": [ ... ]},
    "type": "method", "hits": [ ... ]},
    "type": "organization", "hits": { ... } 
]}
```

NEW API:

```
{
  "OK": true,
  "results": [ ]
}
```

Another difference is that the old API returned every field for each search result, while the new API only returns `id, type, title, lead_image, updated_date` fields.

**Comment by davidascher** [comment]
I think we're done with this.
