### ISSUE TITLE
Allow logged-in users to bookmark a case/method/organization

### ISSUE THREAD

**Issue by davidascher** [participedia/frontend#31]
- [ ] define API (in /api)
- [ ] implement API (in /api), with tests
- [ ] connect bookmark button to said API call (in /frontend), with tests

**Comment by davidascher** [comment]
Blocked on #33

**Comment by davidascher** [comment]
I'm happy to help w/ the back-end bits.

**Comment by andreadelrio** [comment]
@davidascher these are the API calls I would need help with for this feature. 

- get `/bookmarks/userid` --> list of all the bookmarks the user has.
- post `/bookmark/new` --> create new bookmark with user_id, item_type (case, method, organization, etc) and item_id.

- delete `/bookmark/id` --> delete bookmark.

**Comment by davidascher** [comment]
done in #185
