### ISSUE TITLE
Map doesn't maintain position on added search terms (pops open)

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#318]
Not sure if an issue for this exists?

**Comment by davidascher** [comment]
Can you put very precise steps to reproduce please?
1) go to this uRL
2) click on X
3) type in Y
4) expected:
5) actual:

Thanks.

**Comment by jesicarson** [comment]
It seems to be working now, so I'll close this. 
but yesterday:

1. go to: https://participedia.xyz/
2. scroll down the page a bit so the map is about half way below the top menu bar
3. type in a search term in search, hit enter to filter results
4. expected: that the map stays half way below (same position)
5. actual: map pops open to full view
