### ISSUE TITLE
Remove faceted search links from case/method/org pages data

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#319]
so users can't click any of the data facets on a case (because it's confusing and theres no way to see all the facets anyway)

**Comment by jesicarson** [comment]
@dethe will add an api issue to index everything for fulltext search

**Comment by dethe** [comment]
This was done some time ago.

**Comment by dethe** [comment]
Nope, I'm wrong. Just not obvious links until you hover over them.

**Comment by andreadelrio** [comment]
@dethe I'm not quite sure what this issue refers to, can you please explain? maybe a screenshot can help.

**Comment by dethe** [comment]
Metadata in the sidebar shows up as links on hover, and can be clicked to go to a search, but we don't support that type of search anymore, just full-text search. So we need to remove the links around the metadata items (tags, issue, topic, etc.)

<img width="1252" alt="screen shot 2017-08-18 at 8 59 01 pm" src="https://user-images.githubusercontent.com/16825/29483298-27f7909e-8458-11e7-88fe-7e185eec0da1.png">
