### ISSUE TITLE
Admin Feature Request - Editing Cues

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#327]
Via Scott Fletcher - Can we develop an easy way for me to go through and quickly insert some editing 'cues' (eg. the 'broom' icon for "this section needs to be cleaned up" or 'citation needed' etc.)? Wikipedia actually offers all their editing scripts which I had a look through https://en.wikipedia.org/wiki/Wikipedia:Tools/Editing_tools
A lot of them are super simple and definitely applicable to PPedia. For example, the ability to add a note at the end of a sentence that says "awkward phrasing" (in exponential form)

via Pat - We need to discuss whether and how to create this type of editorial community https://medium.com/matter/the-36-people-who-run-wikipedia-21ecca70bcca

**Comment by scottofletcher** [comment]
Unnecessary
