### ISSUE TITLE
Change Map library to Mapscii

### ISSUE THREAD

**Issue by dethe** [participedia/frontend#328]
We can render our maps in pure Unicode, as god and Tim Berners-Lee intended.

<img width="637" alt="screen shot 2017-05-04 at 2 04 34 pm" src="https://cloud.githubusercontent.com/assets/16825/25725007/eea055fc-30d2-11e7-8e13-226ef1c6e6b9.png">
<img width="639" alt="screen shot 2017-05-04 at 2 04 22 pm" src="https://cloud.githubusercontent.com/assets/16825/25725009/ef3722de-30d2-11e7-8af3-131b633a27a5.png">

**Comment by dethe** [comment]
May the Fourth Be With You!

**Comment by davidascher** [comment]
ha.
