### ISSUE TITLE
Usersnap Feedback - Login redirect error still happening. https://participedia.xyz/redirect -Jesi

### ISSUE THREAD

**Issue by davidascher** [participedia/frontend#341]
**Sender**: jesi.carson@gmail.com
**Comment**: Login redirect error still happening. https://participedia.xyz/redirect
-Jesi
[Open #14 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/14)

<a href='https://usersnappublic.s3.amazonaws.com/2017-05-10/07-02/13fce470-0c1b-4cc9-8da0-919f06001c5c.png'>![Usersnap Feedback - Login redirect error still happening. https://participedia.xyz/redirect -Jesi](https://usersnappublic.s3.amazonaws.com/2017-05-10/07-02/c4d66b82-b9d9-43c6-88aa-3674f0f4dab8.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-05-10/07-02/13fce470-0c1b-4cc9-8da0-919f06001c5c.png'>Download original image</a>

**Browser**: Chrome 57 (macOS Sierra)
**Referer**: [https://participedia.xyz/redirect](https://participedia.xyz/redirect)
**Screen size**: 1280 x 800 **Browser size**: 1279 x 676

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by dethe** [comment]
What's the current status of the login issue(s)?

**Comment by davidascher** [comment]
This issue was moved to participedia/usersnaps#19
