### ISSUE TITLE
Edit UI does not give option to remove existing related objects

### ISSUE THREAD

**Issue by dethe** [participedia/frontend#353]
There is an (X) for removing related objects you've just added (before save), but that doesn't appear to work either.

Also, saving edited related objects is sending `value: X` instead of `id: X`, but I've worked around that for now.

**Comment by dethe** [comment]
After more testing it appears to remove all existing related objects when you edit, so you have to add them every time.

**Comment by davidascher** [comment]
should be fixed now.
