### ISSUE TITLE
Default profile picture needed

### ISSUE THREAD

**Issue by davidascher** [participedia/frontend#357]
**Sender**: amberfj@gmail.com
**Comment**: Default profile picture needed
[Open #21 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/21)
**Notes**:
 - (1) We need to design a default profile pic. if picture has not been uploaded by the user.

<a href='https://usersnappublic.s3.amazonaws.com/2017-05-17/19-55/52b067b9-9b9d-4b66-a0dd-69c272492aaf.png'>![Usersnap Feedback - Default profile picture needed](https://usersnappublic.s3.amazonaws.com/2017-05-17/19-55/f4151589-705d-4493-ae76-8f4fac8e992c.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-05-17/19-55/52b067b9-9b9d-4b66-a0dd-69c272492aaf.png'>Download original image</a>

**Browser**: Chrome 58 (macOS Sierra)
**Referer**: [https://participedia.xyz/users/169032](https://participedia.xyz/users/169032)
**Screen size**: 2560 x 1440 **Browser size**: 1622 x 1295

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by davidascher** [comment]
Can you suggest something @samjiangweb ?

**Comment by jesicarson** [comment]
Actually, in our last meeting, we decided to take this off Sam's plate. Also, this is noted in #364, so closing this.
