### ISSUE TITLE
Homepage - Design Updates

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#363]
See [this folder with .ai file & jpgs](https://drive.google.com/open?id=0B5j_dGoSFCLJUE0tNFJSNktaYU0) as layout/ typography guideline for the following:

- [ ] New "featured" treatment - default result on homepage with text header 

- [ ] Search results pagination

- [x] Footer: add logo and text "A global community sharing knowledge and stories about public participation" & make footer black, not grey

- [x] site wide: all text black or red, no grey text

Other: 

- [x] remove underline on mouseover of content titles, just turn red on mouseover OR adjust spacing of underline to allow a bit more space between the text and the line (whichever is easier)

- [x] Rather than grey background box around hamburger on hover, hover turns hamburger icon white.

- [x] Date formatting update (this might be covered in another issue? @samjianga can you confirm?)

- [x] Map: content links are blue - change to site red

- [x] remove "users" from footer

**Comment by samjiangweb** [comment]
@jesicarson Search results pagination should be covered in ticket #192 - date formatting is also covered
