### ISSUE TITLE
Placeholder Image Design Exploration

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#364]
- [ ] Case

- [ ] Method

- [ ] Organization

- [ ] News

- [ ] User Profile Image

**Comment by jesicarson** [comment]
User profile: 

In Stephan's design, we used Google Material user icon in the circle. 

@andreadelrio, can we please implement that design for now? (see the [May 18-Hamburger .ai file](https://drive.google.com/open?id=0B5j_dGoSFCLJTnJZbWQ0UVBHVmc) for the icon) 

The rest of the placeholders that Sam designed are fine for now, so not priority. But we should have something in place for user profile that isn't just blank before the launch. 

![screen shot 2017-05-19 at 12 29 47 pm](https://cloud.githubusercontent.com/assets/13560530/26263807/147f1cfa-3c8f-11e7-8a06-8df5e706b0e5.png)

**Comment by jesicarson** [comment]
a few options:

1
![dec 8 2017 placeholder images homepage mockup](https://user-images.githubusercontent.com/13560530/33786296-6ba944c8-dc1d-11e7-8159-faea7370e6b8.jpg)

2
![dec 8 2017 placeholder images homepage mockup 2](https://user-images.githubusercontent.com/13560530/33786297-6bc156c6-dc1d-11e7-8557-0bac75c95062.jpg)

3
![dec 8 2017 placeholder images homepage mockup 3](https://user-images.githubusercontent.com/13560530/33786298-6bd9d6ec-dc1d-11e7-9ef3-a2495bfe5a74.jpg)

4
![dec 8 2017 placeholder images homepage mockup 4](https://user-images.githubusercontent.com/13560530/33786299-6bf4b494-dc1d-11e7-84a9-d2af3aa89e55.jpg)

**Comment by andreadelrio** [comment]
Amber's feedback: Would be useful to think if those are the metaphors we want to use for case, method and organization. @jesicarson to get in touch with Celeste and ask her to put us in contact with a graphic designer or illustrator.

**Comment by jesicarson** [comment]
Cool. Just emailed Celeste and cc'd you, @andreadelrio.

**Comment by jesicarson** [comment]
Update from Amber (part of the new [Graphic Design Brief](https://docs.google.com/document/d/14WFzwdQdY39aJzVJc6zlAAr2DBNrHP6l8cLl9wa3-5s/edit?usp=sharing)) -
**User profile:** We have an Materials icon which we will use in the short term. The longer term plan is to use initials formatted using Fakt. Jesi and Andrea can handle the long term styling of the initials.
**Placeholder Images for content types:** These do not need individual placeholders by type. Instead we can use a set of 5 placeholder images that are picked and used at random for any of the types.

**Comment by jesicarson** [comment]
Texture exploration 

**Option 1**
![artboard 3-100](https://user-images.githubusercontent.com/13560530/34448223-56f3e23e-eca0-11e7-9ac3-dc79cd55ebf0.jpg)

**Option 2**
![artboard 6-100](https://user-images.githubusercontent.com/13560530/34448233-59ac1a3c-eca0-11e7-97b9-9b939178d47d.jpg)

**Option 3**
![artboard 7 copy-100](https://user-images.githubusercontent.com/13560530/34448235-5c08b268-eca0-11e7-9bb7-d89281c933fd.jpg)

**Option 4**
![artboard 8 copy-100](https://user-images.githubusercontent.com/13560530/34448238-5e1e6836-eca0-11e7-8fc1-c88026280b92.jpg)

**Option 5**
![artboard 9 copy-100](https://user-images.githubusercontent.com/13560530/34448240-5feaf288-eca0-11e7-81a0-69084c32ff44.jpg)

**Comment by jesicarson** [comment]
Amber's feedback Jan 3, 2018:
- Make slightly more comparable in terms of greyness (options 1,2 & 4 are similar, options 3 & 5 are similar - meet in the middle)
- More dense, like e-flux - fill the whole box
- Ask @andreadelrio andrea how to best export to ensure no pixelation and consistent line weight for responsive screen sizing (maybe svg?)
- Can we pull the textures off [e-flux](http://www.e-flux.com/) to take a closer look at them?

**Comment by jesicarson** [comment]
![jan 15 2017 placeholder images homepage mockup](https://user-images.githubusercontent.com/13560530/34957438-7ae74c72-f9e2-11e7-8b89-bd58e972d180.jpg)

**Comment by jesicarson** [comment]
![jan 15 2017 placeholder images homepage mockup2](https://user-images.githubusercontent.com/13560530/34957911-771bc59e-f9e4-11e7-805b-05d53b4b19ed.jpg)

**Comment by jesicarson** [comment]
@andreadelrio  SVG files: https://drive.google.com/open?id=1EbBHWQ7RjRO9njx-JSDfA1BJWeBnGKMK
