### ISSUE TITLE
Add linkedin social icon to footer and content pages

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#365]
https://www.linkedin.com/company/participedia

**Comment by jesicarson** [comment]
I also just realized that the links in the footers are share links - do you think the footer icons should direct people to our actual social pages rather than be share links @samjianga? 
Share links make sense on content pages. 
*Not huge priority, but when you get around to it.

**Comment by andreadelrio** [comment]
Done in ##378

**Comment by jesicarson** [comment]
@andreadelrio linkedin icon still needs to be added to the sidebar below fb and twitter on content pages. I just looked at a case and dont see it yet. 
 
Also, the linkedin icon on the footer looks less sharp on my screen compared to the FB and twitter icons. Is it just me? Thanks!
![screen shot 2017-05-26 at 9 29 57 am](https://cloud.githubusercontent.com/assets/13560530/26503538/efdbccba-41f5-11e7-9dd7-8f630bdc727a.png)
