### ISSUE TITLE
Case/Method/Org Pages - Design Updates

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#366]
See [this folder with .ai files and jpgs](https://drive.google.com/open?id=0B5j_dGoSFCLJUE0tNFJSNktaYU0) for design/ type guidelines:

- [x] Side bar data design update per .ai ("related content" with links in running lists above "data", data not linked, data in running lists, removal of extraneous headers, etc.)

- [x] align lead image with centre column of text 

- [x] and since lead image is smaller, move the bookmark and share icons and the edit over as well. so they are hugging centre column. 

- [x] Header and body typography adjustments per .ai file (header fakt normal, body fakt blond)

- [x] hyperlinks in body text: not bold, just underlined. ensure type size matches body copy.

- [ ] We may want to add a "print" icon... TBC

**Comment by davidascher** [comment]
Not sure who checked off the items in the list above, but I'm not seeing checkins in this issue, so I assume they're not yet done?

**Comment by jesicarson** [comment]
@samjianga I assume?

**Comment by samjiangweb** [comment]
@davidascher @jesicarson the checked off items were addressed in my last merge request

**Comment by jesicarson** [comment]
Covered by: https://github.com/participedia/frontend/issues/589
