### ISSUE TITLE
Mobile - Design updates

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#367]
- [x] move login button to hamburger

- [x] "searching for" / "results" text treatment to match homepage design

- [x] not sure if all footer elements have to match, but if not we can leave the tagline out of the footer on mobile I think. 

- [x] Add LinkedIn social icon to footer.

- [x] Adjust padding on hamburger menu ("home" is cut off and "about" is touching the top menu bar, needs space above)

**Comment by samjiangweb** [comment]
Andrea - We'll need your help on #1 and #4 on this list

**Comment by jesicarson** [comment]
@andreadelrio Here's an updated design for the hamburger:

[Folder w/ .ai file and jpgs](https://drive.google.com/drive/folders/0B5j_dGoSFCLJald4VUVVWEJZSTQ?usp=sharing)

![may 18-hamburger not logged in](https://cloud.githubusercontent.com/assets/13560530/26262534/f85b3536-3c89-11e7-9df1-469ce6282933.jpg)

![may 18-hamburger logged in](https://cloud.githubusercontent.com/assets/13560530/26262546/fde21dda-3c89-11e7-958b-dd94308398d5.jpg)

**Comment by andreadelrio** [comment]
@jesicarson should the LinkedIn button link to Participedia's LinkedIn page or share the site on LinkedIn?

**Comment by jesicarson** [comment]
@andreadelrio in the footer it should go to the Ppedia linkedin page. And also the FB and Twitter icons in the footer should go to participedia's pages. But on the case/ method/ org/ news pages the icons should be to share the article from our site on those platforms. Make sense?

**Comment by andreadelrio** [comment]
@jesicarson Yes. Can I get the links? Thanks!

**Comment by jesicarson** [comment]
https://www.facebook.com/Participedia/
https://twitter.com/participedia
https://www.linkedin.com/company/participedia
