### ISSUE TITLE
Make two column layout work in 1200x800

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#38]
The media queries seem a little off -- a 13" macbook should see the two column layout.

**Comment by davidascher** [comment]
@andreadelrio can you check this?

**Comment by andreadelrio** [comment]
@jesicarson hey Jesi, can you please let me know how to reproduce this? not sure what you mean by two column layout.

**Comment by jesicarson** [comment]
I think it's fine now. I should have taken a screenshot because I can't remember exactly what was happening, but I think I had to zoom out to see things properly and there was some weirdness with the columns. But all looks fine on my computer now. Closing this.
