### ISSUE TITLE
Map is not populated in Safari

### ISSUE THREAD

**Issue by dethe** [participedia/frontend#397]
**Expected/Desired behavior:**

In Chrome and Firefox (on OS X), the map has many pushpins showing case locations, but in Safari these are not showing up. I looked at the network panel and the map data is being delivered from our backend API, so it looks like possibly an issue with the React rendering pipeline that is specific to Safari.

<img width="1272" alt="screen shot 2017-05-31 at 1 36 30 pm" src="https://cloud.githubusercontent.com/assets/16825/26652987/8d770890-4606-11e7-8d82-06de5675e6ad.png">

**Comment by davidascher** [comment]
QuotaExceededError (DOM Exception 22): The quota has been exceeded.

probably localstorage quota.

**Comment by davidascher** [comment]
not sure why this is showing up not in private browsing mode in Safari

**Comment by davidascher** [comment]
works now.
