### ISSUE TITLE
Case Quick submit form needs to be updated

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#399]
Data fields for quick sub from Pat: 

https://docs.google.com/document/d/1apX0QMh43rushoBEGoz_YM1HXn2rlieEX9zJwlBbeDs/edit?usp=sharing

**Comment by jesicarson** [comment]
Note - you don't necessarily have to use Pat's new list of "General Issues" just yet as it will be quicker just to relocate "Issue" from the "do full version" to quick submit.

**Comment by jesicarson** [comment]
Also include tags in quick submit, so we can tag entries as 'oidp2017' to show up in search results.

**Comment by dethe** [comment]
All we need from this for Montreal:

* [ ] Make top-level General Issues the default list in UI for issues, ignore all the other fields from that google doc
* [ ] Move the issue picker and tags into quick submit.

**Comment by jesicarson** [comment]
@dethe will you use pat's new list of general issues or the one currently on .net? And, will you allow people to pick more than one issue or only one? Thanks!

**Comment by dethe** [comment]
@jesicarson I don't see a problem with using Pat's list (it's the other parts of that document that are problematic), but you'll only be able to pick one.

**Comment by jesicarson** [comment]
gotcha, thanks dethe.

**Comment by dethe** [comment]
I think this has been done for some time.
