### ISSUE TITLE
Usersnap Feedback - On submit Method: - There is no "do full version" button (is this build ye[...]

### ISSUE THREAD

**Issue by davidascher** [participedia/frontend#404]
**Sender**: Jesi.carson@gmail.com
**Comment**: On submit Method:
- There is no "do full version" button (is this build yet?)
- Submit button does not work

-Jesi
[Open #34 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/34)

<a href='https://usersnappublic.s3.amazonaws.com/2017-05-31/23-11/7221c1eb-5192-4944-868d-6b82954c01dc.png'>![Usersnap Feedback - On submit Method: - There is no "do full version" button (is this build ye(...)](https://usersnappublic.s3.amazonaws.com/2017-05-31/23-11/c5042f79-a389-4429-8233-c387db6f9b09.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2017-05-31/23-11/7221c1eb-5192-4944-868d-6b82954c01dc.png'>Download original image</a>

**Browser**: Safari 10 (macOS Sierra)
**Referer**: [https://participedia.xyz/new/method](https://participedia.xyz/new/method)
**Screen size**: 1280 x 800 **Browser size**: 1280 x 735

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

**Comment by jesicarson** [comment]
and also: 
- keyword picker doesn't work

**Comment by davidascher** [comment]
This issue was moved to participedia/usersnaps#2
