### ISSUE TITLE
Create/edit Forms: "Other" should not be listed in selection lists

### ISSUE THREAD

**Issue by dethe** [participedia/frontend#406]
We are not supporting user-entered fields for metadata (only for title/body), so we should remove "other" from these lists. If we want a field to express "I would like to fill in this field but none of the options fit" we can use "N/A" or "None of the Above", but "Other" is generally matched up with a field to enter a new value not on the list.

**Comment by davidascher** [comment]
Some of the data has `other` as a value for some of these fields.  Are we saying we want that to be a read-only value?  Not sure what would happen if someone edits such a case/method/etc.

If you can point to an example maybe it'll help me understand specifically what you mean.

**Comment by dethe** [comment]
Nevermind, we can keep "Other" it just won't allow users to add random data.
