### ISSUE TITLE
Submit Case, Method & Org - move left side bar ("do full version") to centre column *Pre Montreal

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#407]
Put all fields below quick submit fields and two buttons: "Quick Submit" and "Do full version" (match button design to top nav "quick sub" button)
- Clicking "Quick submit" publishes the article and directs the user to the published page for that article
- Clicking "Do full version" publishes the article (the quick sub version will show up in results), but the user remains on the submit page, and the rest of the form is revealed below, in the same column (not on the left)

* shifting these forms to the centre column will solve some of the overlapping content issues being caused by the narrowness of the left column. 

* Methods and Orgs need the full version forms added (currently only quick submit fields are available)

**Comment by davidascher** [comment]
@jesicarson -- I'm not sure the "do full version" logic you describe (submit in the background) above is super intuitive.  What I have it do now is show the full fields, but not submit until people hit the submit button at the end.  Give that a shot and let me know if it feels ok.

**Comment by jesicarson** [comment]
@davidascher do we have a way for people to save their work before it's published? Just trying to avoid lost work. Also, what if I change my mind and I only want to quick submit after I see how long the forms are? Maybe theres another way to achieve this... But perhaps we don't worry about it for now. Would be good to get the forms updated tho (issue #399)
