### ISSUE TITLE
URL for OIDP2017 results should be cleaned up

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#412]
ie: www.participedia.xyz/search/oidp2017 (or something)

**Comment by davidascher** [comment]
From a technical PoV:

add a route that maps `/search/<word>` to `/search/query?<word`

**Comment by davidascher** [comment]
@jesi: `/show/oidp2017` will redirect to the right search.  Not gorgeous, but it'll work and you can use it in slides, etc.

**Comment by jesicarson** [comment]
@davidascher cool!
