### ISSUE TITLE
Auth0 breaking locally (and maybe on prod?)

### ISSUE THREAD

**Issue by dethe** [participedia/frontend#413]
When I load up the latest frontend code and run `yarn upgrade` to get all the dependencies up to date, I get:

<img width="1184" alt="screen shot 2017-05-31 at 6 01 23 pm" src="https://cloud.githubusercontent.com/assets/16825/26660278/cf0c793c-462b-11e7-8cac-a15ee8df2fda.png">

I have poked around in `src/utils/AuthService.js` trying to figure out where `this.auth0` and `this.auth0.client` get set, with no luck so far.

Possibly related: on the API side, when we are logged in and visit `https://api.participedia.xyz/user` it is returning a 401 error from `ensureUser()`, which means there was no user object attached to the request.

**Comment by davidascher** [comment]
What if you don't yarn upgrade?

**Comment by dethe** [comment]
Server wasn't starting, that's why I ran yarn upgrade.

**Comment by davidascher** [comment]
npm install & npm start didn't work? hard to believe that's related to auth0

**Comment by dethe** [comment]
I'm a bit confused when to use npm and when to use yarn, but npm install and npm start give me the same error. In the console I get the following warnings:

```
./src/Layout.js
[1]   Line 61:  'handleAuthentication' is assigned a value but never used  no-unused-vars
[1] 
[1] ./src/utils/AuthService.js
[1]   Line 4:   'auth0' is defined but never used                  no-unused-vars
[1]   Line 10:  'AUTH_VERSION' is assigned a value but never used  no-unused-vars
[1]   Line 15:  'AUDIENCE' is assigned a value but never used      no-unused-vars
```

**Comment by davidascher** [comment]
Those are just warnings.  

npm and yarn can be used interchangeably.  npm4 is slower, npm5 is as fast.

**Comment by dethe** [comment]
Yeah, just thought the warnings might give a clue. All the tests pass, except one snapshot, which is probably just due to the issue you and Andrea have been wrangling.

**Comment by davidascher** [comment]
snapshot should be fine on master. paste whatever isn't right, happy to help debug if I can see what's not working.

what's not actually working w/o upgrade?

**Comment by dethe** [comment]
I don't remember now, I guess I can roll back to the earlier version, run npm install, then come back to HEAD to check.

Snapshot failure is:

```
FAIL  src/__tests__/Method-test.js
  ● ItemDetails for Method renders correctly

    expect(value).toMatchSnapshot()
    
    Received value does not match stored snapshot 1.
    
    - Snapshot
    + Received
    
    @@ -140,11 +140,11 @@
                   >
                     <time
                       dateTime="2011-12-01T19:31:01.000Z"
                       title="2011-12-01T19:31:01"
                     >
    -                  5 years ago
    +                  6 years ago
                     </time>
                   </p>
                 </div>
                 <div
                   className="case-html"
      
      at Object.<anonymous>.test (src/__tests__/Method-test.js:79:16)
      at Promise.resolve.then.el (node_modules/p-map/index.js:42:16)
```

**Comment by dethe** [comment]
Fixed by `localStorage.clear()`
