### ISSUE TITLE
Fix profile view for some users

### ISSUE THREAD

**Issue by davidascher** [participedia/frontend#431]
Profile API calls work for me, not for @jesicarson. My guess is some database initialization issues.

**Comment by dethe** [comment]
@jesicarson This works for you now, right?

**Comment by jesicarson** [comment]
It does, I can view my profile. But it looks like a bunch of cases are duplicated, FYI.

**Comment by dethe** [comment]
I think I have a separate issue for that, but will make sure it gets fixed, thanks!
