### ISSUE TITLE
figure out how to extract last author information

### ISSUE THREAD

**Issue by davidascher** [participedia/frontend#47]
Ref. [src/containers/Case.js:79](https://github.com/participedia/frontend/blob/3aa4e6a29e5bf009a1a6c4bde47621d9b92c3911/src/containers/Case.js#L79)

``` js
      let last_author = '???' // TODO figure out how to extract last author information
      let id = this.props.params.nodeID
      let editLink = (<Link to={`/${locale}/case/${id}/edit`} />)

…
```

(automatically generated by [Github-Todos](https://github.com/naholyr/github-todos))

**Comment by davidascher** [comment]
Ref. [src/containers/Case.js:79](https://github.com/participedia/frontend/blob/3aa4e6a29e5bf009a1a6c4bde47621d9b92c3911/src/containers/Case.js#L79)

```js
      let last_author = '???' // TODO figure out how to extract last author information
      let id = this.props.params.nodeID
      let editLink = (<Link to={`/${locale}/case/${id}/edit`} />)

…
```

(automatically generated by [Github-Todos](https://github.com/naholyr/github-todos))

**Comment by davidascher** [comment]
Note for @dethe do we have a list of authors involved in the history of a case/method/etc?

**Comment by dethe** [comment]
Right now it is a list of one, but we'll have this going forward.

**Comment by davidascher** [comment]
working.
