### ISSUE TITLE
Failure to find mini-map shows ugly error

### ISSUE THREAD

**Issue by dethe** [participedia/frontend#472]
On Mac / Chrome.

I hadn't even finished submitting this case (perhaps a stray keypress accidentally submitted?), but had chosen a location in South Africa, got an error page and then this:

<img width="774" alt="screen shot 2017-06-16 at 8 09 07 pm" src="https://user-images.githubusercontent.com/16825/27249687-095ec922-52d0-11e7-88b9-e22b1c0a2289.png">

It seems like we're having trouble finding an SVG map file for South Africa, but even in that case we should have a less catastrophic-looking fail state.

**Comment by davidascher** [comment]
Agreed.

We need to shift from an `<img>` to a component that does an XHR and then processes the result.
