### ISSUE TITLE
Make sure that map view reflects selectedType

### ISSUE THREAD

**Issue by davidascher** [participedia/frontend#478]
See https://github.com/participedia/usersnaps/issues/35

**Comment by davidascher** [comment]
@dethe what's your thinking on this topic given the ongoing conversation about pins?

**Comment by dethe** [comment]
We can still return all the locations from the map query, but only mark the filtered ones as selected, so the others will be grayed out and unclickable.

**Comment by davidascher** [comment]
Blocked on an API bug AFAICT.
