### ISSUE TITLE
load real images in Case details */

### ISSUE THREAD

**Issue by davidascher** [participedia/frontend#48]
Ref. [src/containers/Case.js:143](https://github.com/participedia/frontend/blob/3aa4e6a29e5bf009a1a6c4bde47621d9b92c3911/src/containers/Case.js#L143)

``` js
                    {[0, 1, 2].map(function (obj, i) { /* TODO load real images in Case details */
                      return (
                        <div className='thumbnail' key={i}
                          style={{ backgroundImage: 'url(/img/placeholder/400_' + getRandomInt(0, 30) + '.jpeg)' }} />
…
```

(automatically generated by [Github-Todos](https://github.com/naholyr/github-todos))

**Comment by davidascher** [comment]
Ref. [src/containers/Case.js:143](https://github.com/participedia/frontend/blob/3aa4e6a29e5bf009a1a6c4bde47621d9b92c3911/src/containers/Case.js#L143)

```js
                    {[0, 1, 2].map(function (obj, i) { /* TODO load real images in Case details */
                      return (
                        <div className='thumbnail' key={i}
                          style={{ backgroundImage: 'url(/img/placeholder/400_' + getRandomInt(0, 30) + '.jpeg)' }} />
…
```

(automatically generated by [Github-Todos](https://github.com/naholyr/github-todos))

**Comment by andreadelrio** [comment]
Already working on this in #24.

**Comment by davidascher** [comment]
yes, this was a test of an automated issue creator.  I'll close it, it's not useful
