### ISSUE TITLE
Profile view bookmarked content doesn't show filled in bookmarks

### ISSUE THREAD

**Issue by davidascher** [participedia/frontend#496]
and likely authored content isn't showing bookmarks as well.

**Comment by andreadelrio** [comment]
There's something weird going on with authored content too (same case shows up multiple times)
![image](https://user-images.githubusercontent.com/4016496/27519189-80c9e490-59a3-11e7-8f08-e80243a5c726.png)

**Comment by dethe** [comment]
Fixed in PR #533
