### ISSUE TITLE
add video link editor for cases/methods/orgs and add videos to details pages

### ISSUE THREAD

**Issue by davidascher** [participedia/frontend#499]
We want:

- when editing a case/method/org, to have the ability to add a link to one or more youtube or vimeo URLs
- to have those URLs stored by the API using the `videos` field of things.  This field should be an array of URLs.
- when viewing a detailed case/method/org, use a widget to let people play/pause etc. that video in the page.

Steps:

- the API will already return `videos` fields if they exist
- for editors, modify `CaseEditor`, `MethodEditor`, `OrganizationEditor` to have a `Field` that's just like the solution for `links`.  In fact you can probably reuse `makeLocalizedListField` at first, although I think we will want to over time move to a setup where we check that the links are indeed links to video hosting sites that the widget knows how to play
- for details view, modify `CaseDetails` etc with a widget (make sure it knows how to deal with youtube vs. vimeo links for example).

The `Field` widget is part of 'simple-react-form`, which is worth reading about.  The `Form` takes the object in question, extracts the fields for each `Field`, sends the value at the time of rendering to the component specified by the `type` field in the `Field`, and expects that component to call the `onChanged` prop that it is passed.  It's confusing, but look at the other `PropEditors` for the model (if you need it -- you probably only need to dig into that to do validation)

Ask if you have questions!

**Comment by andreadelrio** [comment]
Covered in #539
