### ISSUE TITLE
SEARCH: revise placeholder images for case, method, org, user

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#50]
4:3 image for case, method, org, user if no image available

**Comment by davidascher** [comment]
I think @samjiangweb dealt with this.

**Comment by jesicarson** [comment]
Post-meeting update:

@samjianga will revisit this design. 

Possible suggestions:

- you could try a semi-transparent version of the icon at a larger scale behind the middle icon, maybe off centre (to add texture) 
- brainstorm ideas for visually interesting textures / patterns that could be randomly placed (is there such thing as a participatory texture? lol)
- maybe there's another solution rather than the grey background box? Perhaps this is softening up the black and white look too much.

**Comment by jesicarson** [comment]
Example of cool placeholder texture, in this case during image loading time - http://www.e-flux.com/

**Comment by davidascher** [comment]
https://www.toptal.com/designers/subtlepatterns/ has a lot of textures

**Comment by dethe** [comment]
Done, some time ago.
