### ISSUE TITLE
Create thumbnailer component for youtube/etc links

### ISSUE THREAD

**Issue by davidascher** [participedia/frontend#52]
As indicated in https://github.com/participedia/frontend/issues/51 we need a way to thumbnail videos, first in detail view pages, then ideally in the submission process.

**Comment by davidascher** [comment]
See https://github.com/troybetz/react-youtube

**Comment by davidascher** [comment]
https://github.com/CookPete/react-player is a better fit (more generic)

**Comment by andreadelrio** [comment]
Depends on #202
