### ISSUE TITLE
Mockup for Case Quick Submit

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#522]
[Folder in drive](https://drive.google.com/open?id=0B5j_dGoSFCLJVFE2OXloN0ZCNFE) has .ai file for reference. 

Reference issues #399 & #436 

![case quick sub](https://user-images.githubusercontent.com/13560530/28050508-fc33bd7a-65b2-11e7-813d-e5bdb94a8243.jpg)

**Comment by dethe** [comment]
@andreadelrio If you have time to look at this, let me know. I'll need to make sure the API will accept Cases with no `body` field.

**Comment by andreadelrio** [comment]
@dethe I can take care of this one, we can go over the details tomorrow.

**Comment by andreadelrio** [comment]
@jesicarson could you provide something similar for both `method` and `organization`?

**Comment by jesicarson** [comment]
@andreadelrio definitely! I'll get on it asap.

**Comment by jesicarson** [comment]
Slight change to tags on this mockup. Should say "Type to search for an existing tag" 

![july 19 17 case quick sub](https://user-images.githubusercontent.com/13560530/28394688-a624df3e-6ca3-11e7-9ac5-7f4a6b0e728b.jpg)

**Comment by dethe** [comment]
Fixed in PR #534 and pushed to xyz.
