### ISSUE TITLE
Replace black thumbnails with images for video players

### ISSUE THREAD

**Issue by dethe** [participedia/frontend#540]
If we can use a frame of the video as an image for these, that would be perfect, but I don't know how much work that would be. 

* [ ] Figure out if we can do it
* [ ] Figure out how hard it would be
* [ ] If we decide it is still worthwhile, implement

**Comment by jesicarson** [comment]
@dethe @andreadelrio wouldn't there automatically be a frame from the video for the thumbnail if the video link was from youtube or vimeo? Whoever uploads to vimeo/ youtube choses the thumbnail frame and thats what shows up on social cards, could we do that?

**Comment by jesicarson** [comment]
Mocks from homepage video display design [here](https://drive.google.com/open?id=0B5j_dGoSFCLJSlJ4SnFHZll6d0E). Can't find an issue for that, although Andrea and I were chatting about it on Slack in late July. 
![july 27 homepage video thumbnail display-hover pause](https://user-images.githubusercontent.com/13560530/29886593-6e40c50a-8d6f-11e7-94aa-080805203b8b.jpg)
![july 27 homepage video thumbnail display-hover play](https://user-images.githubusercontent.com/13560530/29886592-6e3cac0e-8d6f-11e7-862b-9018b6738f7a.jpg)

**Comment by andreadelrio** [comment]
Already covered.
