### ISSUE TITLE
Misdirect from list of cases in user profile

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#552]
From  @plscully. Reference [this document](https://docs.google.com/document/d/1PPHqXanIS0SMdS4KIFSDEev74xUCB4EU4ozbLeW89wk/edit?usp=sharing)

Misdirect from list of cases in user profile: I selected [Gabriel Walker’s user profile](https://participedia.xyz/users/114542) via the link on one of his cases. When I then selected another one of the cases listed in his profile, I was sent to [this page](https://www.dropbox.com/s/8j5m3y23846nhaf/Screenshot%202017-08-09%2017.58.53.png?dl=0). The same thing happened with a few other profiles I tested.

**Comment by andreadelrio** [comment]
@dethe is currently fixing this on the API.
