### ISSUE TITLE
Next/back buttons sometimes go wrong

### ISSUE THREAD

**Issue by dethe** [participedia/frontend#556]
Earlier today, on the front page, the `>` button to go to the next page of results was going to `/case/1?page=3` instead of `/?page=3`. @andreadelrio says she's seen that too, sometimes. When we tried to reproduce it we couldn't. Not sure what caused it or how to reproduce yet.

**Comment by dethe** [comment]
Sometimes forward next can even take you to Quick Submit?!?

https://github.com/participedia/usersnaps/issues/59

**Comment by davidascher** [comment]
I believe this is fixed.  reopen if not.
