### ISSUE TITLE
Quick subs should include a tweet-length description (post-user testing, mockups needed)

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#571]
@plscully this wasn't included in your provided quick sub fields, however each time I do a quick sub I feel like it's missing something. Thoughts?

**Comment by plscully** [comment]
@jesicarson -- I agree. Let's add a tweet-length description. ... How would this function relate to a type of "summary" field that's on the old site? Are you thinking that we don't need a summary option (or the default of displaying a trimmed version of the article body) b/c the new display doesn't call for that?

**Comment by jesicarson** [comment]
@plscully ok great. I think on the list view display of search results we have plenty of space to add a short description, so it could work almost exactly the way "summary" does now. It will ideally also be useful for sharing social cards (which reminds me to ask @dethe about how to set that up so it's nice and clean for social sharing). 

I have to think about where this short description would display on the article reader view though (or if it should?). I suppose above the article body, but we want it to be clear that it's like a brief intro to the case/method/org... I'll put it on my list of mockups to work on and we can address it after user testing.

**Comment by dethe** [comment]
This was added as part of the Case form overhaul. Will be added to Methods and Organizations as we update those forms.
