### ISSUE TITLE
Show data on mobile for cases, methods, orgs. (ideally pre-user testing)

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#573]
Might need mockups, unless just a bug? @andreadelrio can you confirm if we're supposed to be showing data and if you need mocks? Thx!

Ideas for design:
maybe a button similar to the "Edit All" vs. "Quick Submit". That may be a pattern we want to standardize across the site.
Maybe an accordion thing like we do in the about pages but for "related content" and "case data". Typographic formatting should match the desktop version anyway.

**Comment by andreadelrio** [comment]
@jesicarson yes we'd need mocks to know how to display that data in mobile. Right now we hide that sidebar for mobile.

**Comment by jesicarson** [comment]
@andreadelrio on it, thanks!

**Comment by jesicarson** [comment]
@andreadelrio 

.ai [here](https://drive.google.com/open?id=0B5j_dGoSFCLJQ3c2QTVqWVNvdHc)

![10 copy 4-100](https://user-images.githubusercontent.com/13560530/29689531-5f1672aa-88d8-11e7-9aa3-91dbb47503be.jpg)

![10 copy 5-100](https://user-images.githubusercontent.com/13560530/29689530-5f13b394-88d8-11e7-9b8b-e6606f059ef5.jpg)
