### ISSUE TITLE
Related links need protocols

### ISSUE THREAD

**Issue by dethe** [participedia/frontend#575]
When we convert a "related link" into an actual link on the page we need to make sure that it has a protocol (defaulting to `http://` if there isn't one), otherwise it will try to load the url as a path on the xyz domain.

You can see this in actions on https://participedia.xyz/case/4606 where the text `www.jesicarson.com` is linked to the non-existent page `https://participedia.xyz/case/www.jesicarson.com`.

**Comment by andreadelrio** [comment]
@dethe Sorry for not catching this earlier. Just submitted a PR to fix it.

**Comment by dethe** [comment]
Fixed in PR #576
