### ISSUE TITLE
Clicking "Participedia" does not clear search

### ISSUE THREAD

**Issue by dethe** [participedia/frontend#577]
Clicking the "Participedia" logo / word mark at the top left of the page does not clear the search terms or paginations, but does switch from filtered results (i.e., only cases, methods, OR organizations) to all results.

Expected results: all filters, paginations, and search terms would be cleared and we get back to the "home view" of the default search.

**Comment by dethe** [comment]
Related:
https://github.com/participedia/usersnaps/issues/11

**Comment by davidascher** [comment]
fixed.
