### ISSUE TITLE
Map pin popups need more data shown

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#584]
Jesi will provide mockups.
Not required before user testing.

**Comment by jesicarson** [comment]
For design review:

Option 1
![screen shot 2017-11-02 at 5 34 01 pm](https://user-images.githubusercontent.com/13560530/32456801-be92243a-c2db-11e7-93a5-64810f9c0dba.png)

Option 2
![screen shot 2017-11-02 at 5 34 27 pm](https://user-images.githubusercontent.com/13560530/32456802-beaa6914-c2db-11e7-9ea2-291915f9415a.png)

Option 3
![screen shot 2017-11-02 at 5 34 38 pm](https://user-images.githubusercontent.com/13560530/32456803-bec222fc-c2db-11e7-9090-1b47b7d1ac7f.png)

**Comment by jesicarson** [comment]
@andreadelrio 
Notes from Nov 20 D&T meeting:

- [ ] Add submitted by 
- [ ] Check bookmarking

*Maybe add summary (if we can get around the “PROBLEMS AND PURPOSE” header from clipped body when summary is empty), related to #659

**Comment by jesicarson** [comment]
- [ ] add distinguishable marker on popups of RED PINS (ie: this matched your search or this is a featured case)

**Comment by andreadelrio** [comment]
@jesicarson I think putting a snippet of the body is going to be tricky because we have a lot of different common headers we'd need to remove. Also, it'd be a crowded popup, so I'd advice against it.

What do you think of this for the red pins?
![image](https://user-images.githubusercontent.com/4016496/34745195-8a0d5de2-f544-11e7-95ac-9b6826bfde2e.png)

**Comment by jesicarson** [comment]
@andreadelrio 

Thanks for this. Looking good so far! I hear you about including the short description... I think we can be ok with leaving that out (let's ask Amber).

I see some typographic hierarchy and spacing issues with the layout of the popup text - can you compare to the mockup and see if you can improve? (Match to the layout of the CASE Title and Submitted by text in the grid below)

I also think we should find a different location for the "this matched your search" text, as it is not part of the data. Perhaps the very bottom, aligned with the X? 

Thanks!!
