### ISSUE TITLE
Can't add videos to xyz

### ISSUE THREAD

**Issue by andreadelrio** [participedia/frontend#599]
When I try to create a new case I get
```
Something went wrong
{}
```

When I try to edit a existing case (e.g. 4618) I get

![image](https://user-images.githubusercontent.com/4016496/29889968-9f3c03c4-8d8b-11e7-8393-9a5f1373731c.png)

- No problems locally.
- Editing other fields works fine.

**Comment by dethe** [comment]
Good catch. Especially interesting, since I'm not seeing this error locally.

**Comment by dethe** [comment]
We had missed a migration on xyz (changes made to the database schema for videos). Automating this will happen in https://github.com/participedia/api/issues/93 so we avoid this issue in the future.
