### ISSUE TITLE
Suggested User Profile Page Edits

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#60]
- [ ] Notifications (ie: when your published work is edited by another user)
- [ ] Auto import profile data from social networks (ie: bio from linkedin)
- [ ] Connect to users who publish similar content (ie: suggested users filter in search)
- [ ] Add bookmark option to content displayed in search
- [ ] Visual completeness indicator for content displayed in search

**Comment by davidascher** [comment]
I think we should break each of these into a new issue, that we prioritize.
