### ISSUE TITLE
Cleanup CSS on geosuggest.scss in /profile/edit

### ISSUE THREAD

**Issue by davidascher** [participedia/frontend#61]
See https://github.com/ubilabs/react-geosuggest for pointers to the kind of CSS expected.

Current dropdown is a bit ugly

<img width="588" alt="screenshot 2016-10-31 22 48 21" src="https://cloud.githubusercontent.com/assets/51278/19880629/2ea7dc72-9fbc-11e6-9f97-8c3036eae63c.png">

**Comment by davidascher** [comment]
Note some CSS is in EditProfile.scss as well. Refactor at will

**Comment by andreadelrio** [comment]
Please see PR #77
