### ISSUE TITLE
Broken images

### ISSUE THREAD

**Issue by andreadelrio** [participedia/frontend#62]
Some images paths and names are corrupt and are not found on AWS.

Case 1:
http://www.participedia.net/sites/default/files/styles/medium/public/eu_logo.jpg
http://assets.participedia.xyz.s3.amazonaws.com/eu_logo.jpg [not working]

Case 1 is displaying the following as the lead_image field

```
<div id="file-773" class="file file-image file-image-jpeg">

        <h2 class="element-invisible"><a href="/en/file/773">e-delib_circles_grc.jpg</a></h2>
    
  
  <div class="content">
    <img typeof="foaf:Image" src="http://www.participedia.net/sites/default/files/e-delib_circles_grc.jpg" alt="" title="" />  </div>

  
</div>
```

Case 2:

http://participedia.net/sites/default/files/styles/medium/public/e-delib_circles_grc.jpg
http://assets.participedia.xyz.s3.amazonaws.com/e-delib_circles_grc.jpg [not working]

**Comment by andreadelrio** [comment]
Case 3: 

http://www.participedia.net/sites/default/files/styles/medium/public/pepperdine-university.jpg
http://assets.participedia.xyz.s3.amazonaws.com/pepperdine-university.jpg [not working]

**Comment by davidascher** [comment]
I believe I have fixed this.
