### ISSUE TITLE
Map questions from Pat

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#622]
Aug 30
There’s no rush on this (in fact, I will be away on vacation and mostly offline starting tomorrow through next Wednesday), but could you please tell me more about the design decisions that were made about the map?  I always seem to be unable to see part of the northernmost or southernmost part of the globe when it is in the default position. I can move around on the map to see different parts of the entire world, but the default position leaves something out. I may be slow, but it doesn’t feel very intuitive for me. For ex.,  Fullest minimization on Chrome (https://www.dropbox.com/s/cydwvm6um2qpvxs/Screenshot%202017-08-31%2014.18.56.png?dl=0) – Can’t see most of N America and Europe. And with this one I can’t see big parts of the So hemisphere -- https://www.dropbox.com/s/auyj05y4nkinvvy/Screenshot%202017-08-31%2014.26.43.png?dl=0
- pat

**Comment by dethe** [comment]
Changed default zoom and centring. See https://ppedia.surge.sh/ for demo. Happy to tweak this as needed, but closing for now. Feel free to open a new issue with specific zoom and/or lat/long centring requests.
