### ISSUE TITLE
Editing some cases doesn't show main content area

### ISSUE THREAD

**Issue by davidascher** [participedia/frontend#628]
go to https://participedia.xyz/case/4512/edit when logged in

I'm not seeing the main text editor being shown.  haven't dug into why.

**Comment by davidascher** [comment]
I guess it's apparently by design -- we have the main description/narrative in the full edit view. Feels weird to me.  @jesicarson what do you think?

**Comment by jesicarson** [comment]
Yes, we don't want the full narrative in quick submit. Not quick. 

But we are coming back to the idea of a tweet length description in quick sub - have to figure out how this interacts with full narrative (probably like the summary field works now on .net. Also could be useful if we want to add text to the list view of search results).

All this said, there was some feedback in user testing that folks were overlooking the fact that there is a full version at all - so this needs to be addressed.
