### ISSUE TITLE
Narrative Jumping Screen Bug

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#632]
**Robert Richards (iPhone SE, Safari browser)** "Editing was difficult on mobile. Every time that I entered data, the browser pushed me up to the field called "Case Description Narrative". As a result, I could not see the data I was entering. After every key stroke, I had to scroll down to the field I was editing."

**Comment by jesicarson** [comment]
**Scott Fletcher**
"When I edit a case and press 'enter' for a new paragraph I'm immediately returned to the top of the narrative entry box (eg. I was entering the 'Influence, Outcomes, and Effects section, pressed enter for a new paragraph, and found myself at 'Problems and Purpose'. I scrolled down to where I'd left off and pressed backspace (to cancel the new paragraph) and the same thing happened - my page scrolled up to 'Problems and Purpose'.)"

**Comment by jesicarson** [comment]
**Marco Adria (iPhone 6S, Safari)**
"I was able to edit the main fields at the top (Name of Case, and so on) with no problems. The "Full Version" at the bottom (Problems and Purpose, and so on), which required typing, was difficult - the screen kept jumping back and forth, up and down, with each stroke, so I gave up."

**Comment by jesicarson** [comment]
**Lucy Parry (iPhone 5S, Safari)**
"When I tried to add/delete/edit some additional text in the main description window, the screen kept jumping around. I can only delete/add one letter then it jumps around. Tried several times. Couldn't complete the task."

**Comment by andreadelrio** [comment]
This seems to be an issue with [ReactQuill](https://github.com/zenoamaro/react-quill). It's also happening on desktop. Haven't been able to find any workarounds yet.

**Comment by dethe** [comment]
Fixed in PR #660
