### ISSUE TITLE
Underscores between words on sidebar data

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#633]
see example: https://participedia.xyz/case/4633

![screen shot 2017-09-26 at 4 27 11 pm](https://user-images.githubusercontent.com/13560530/30888847-9fd60382-a2d7-11e7-8388-fd4853701975.png)

**Comment by jesicarson** [comment]
Also the font on tags is wrong.

**Comment by andreadelrio** [comment]
![image](https://user-images.githubusercontent.com/4016496/30985710-f3cb9ff0-a445-11e7-9ea9-54d67ea281a2.png)
(above: old, below: newly created case)

This is only happening to new cases.
@davidascher could this be happening because of the changes to intl?
