### ISSUE TITLE
Update FAV Icon

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#650]
Design needed. Not priority. 

![screen shot 2017-09-27 at 4 39 53 pm](https://user-images.githubusercontent.com/13560530/30942932-86076b78-a3a2-11e7-8815-bed42150cf4b.png)

**Comment by andreadelrio** [comment]
![favicon_1](https://user-images.githubusercontent.com/4016496/33913065-1c9d436a-df4d-11e7-860a-5fa673567fc6.png)

**Comment by scottofletcher** [comment]
I agree with @andreadelrio - are the orange lines in the blue icon supposed to be wavy or is it just my eyes?

**Comment by jesicarson** [comment]
@scottofletcher the first screenshot shows what we have now on xyz (the old colour scheme and, yes, pixelated), which we're updating with this issue.

**Comment by andreadelrio** [comment]
Amber's feedback: Ok to go forward with current proposal, might want to revisit this if we hire a graphic designer/illustrator.
