### ISSUE TITLE
Bookmarks should not be shown when not loggged in

### ISSUE THREAD

**Issue by dethe** [participedia/frontend#651]
Currently you can see the bookmark icon whether you are logged in or not, but if you try to bookmark something it causes an error. We could log someone in when they try to add a bookmark, but probably less surprising to only show the bookmark button when they're logged in already.

**Comment by jesicarson** [comment]
I'm torn about not showing bookmarks when not logged in. It might make someone want to create an account? I think I'd vote for logging in when someone tries to bookmark..

**Comment by dethe** [comment]
Fixed this ages ago, it now prompts you to log in when you click the bookmark icon.
