### ISSUE TITLE
Design needed for user profile page

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#655]
Ref: https://github.com/participedia/usersnaps/issues/84

**Comment by jesicarson** [comment]
- when you login with gmail, don't show the email address as username, use name
- no mail/ messaging icon
- figure out pagination / jump to bookmarks / other system (maybe tabs like homepage) in case results of authored content is a really long list 
- visual match to homepage with rule line / grid/ list
![screen shot 2017-10-18 at 1 42 01 pm](https://user-images.githubusercontent.com/13560530/31741806-6f7f1a9a-b40a-11e7-9e48-cb08e0089b01.png)
- prof pic edit
- form update (Organization - type to search for an organization on participedia or enter the name of the company or organization that you work for) // wysiwyg editor for bio

**Comment by jesicarson** [comment]
Hey @andreadelrio something to consider - on .net we actually do offer users the option to allow other users to contact them via a personal contact form. So could potentially have the mail icon appear if the user selects that setting. Or not?
![screen shot 2017-10-20 at 3 48 24 pm](https://user-images.githubusercontent.com/13560530/31844582-7c061f8e-b5ae-11e7-96a7-87ce079db913.png)

**Comment by jesicarson** [comment]
@andreadelrio When you get a chance, no rush, please create a dated folder in the mockups folder and save your current work there, for future reference. If you're doing mocks, good practice just to work from that folder so we can have an archive of the work on design. 

I'd also like to ask about the idea of messaging (as noted in my last comment above), I remember you had the message button in your mockups, that was visible to others, and then it was an edit button when viewing your own profile. (side note: I actually think this might be a better solution than the edit button in the corner - I actually missed it, even though I knew it was there, and went looking for edit profile elsewhere! lol)

But about messaging, are you including this as a setting? and we should talk about where user settings vs. edit profile show up, how they get there, etc. Here's the mockup I did for settings a while back: 
![artboard 87 copy 3-100](https://user-images.githubusercontent.com/13560530/32187303-e1df8614-bd61-11e7-8261-fe8e7d21900c.jpg)

**Comment by jesicarson** [comment]
@andreadelrio We talked to pat and decided to only provide a bio text field for the user profile - no additional data fields.

**Comment by jesicarson** [comment]
Notes from Nov 20 D&T meeting:

- Can we generate initials for a profile? Prioritize
- Use icon of user for now ([material icon](https://material.io/icons/#ic_account_circle))
- Use a button for “Edit profile” in top right corner, always visible
- “Nothing yet” - steer people to add content, include a button maybe or explain that they can add and bookmark content
- Spacing below the profile picture should be the same as above (in case ppl dont enter bio)

@andreadelrio some of these things can be done easily, others will require a mockup (like the nothing yet thing). we can discuss tomorrow.

**Comment by andreadelrio** [comment]
Proposals for handling "Nothing yet"
![image](https://user-images.githubusercontent.com/4016496/33226250-3a3c1d6e-d13e-11e7-97bc-d98aa568eb13.png)
![image](https://user-images.githubusercontent.com/4016496/33226256-4c6ca8d2-d13e-11e7-811c-eaa30456de4b.png)

**Comment by jesicarson** [comment]
Looks good!

**Comment by andreadelrio** [comment]
@jesicarson Styling options for the "Nothing yet" prompt message below

Option A
![gray_1](https://user-images.githubusercontent.com/4016496/33416652-a14f59a4-d552-11e7-89a0-56bf2d92945f.png)
Option B
![gray_2](https://user-images.githubusercontent.com/4016496/33416653-a1657d56-d552-11e7-8bcd-8c09f74e40a4.png)
Option C
![red_1](https://user-images.githubusercontent.com/4016496/33416654-a17f393a-d552-11e7-82c6-e3f63423047c.png)
Option D
![red_2](https://user-images.githubusercontent.com/4016496/33416655-a196f548-d552-11e7-8c74-3f1c6b1ed3cd.png)

**Comment by andreadelrio** [comment]
@jesicarson here are the "edit profile" button options with and without bio text.

Edit profile button (to the right) - w/ bio
![edit_profile_on_right](https://user-images.githubusercontent.com/4016496/33418554-40d2169e-d55b-11e7-99a5-f6603545aed8.png)

Edit profile button (to the right) - No bio
![edit_profile_on_right_no_bio](https://user-images.githubusercontent.com/4016496/33418696-f215d6a2-d55b-11e7-9482-4d836c257f1d.png)

Edit profile button (below) - w/ bio
![edit_profile_below](https://user-images.githubusercontent.com/4016496/33418555-4112f47a-d55b-11e7-9fea-a559107b2628.png)

Edit profile button (below) - No bio
![edit_profile_below_no_bio](https://user-images.githubusercontent.com/4016496/33418700-f62224b2-d55b-11e7-9f35-7da64948df00.png)

**Comment by scottofletcher** [comment]
Are these finalized? If not, I'd like to give my two cents: first proposals to 'nothing yet' are better than ABC or D. Edit button to the right (w/ or w/out bio) is preferable (otherwise I think I'm just changing my picture rather than my bio and my picture)

**Comment by jesicarson** [comment]
Thanks @scottofletcher! Not finalized, and Andrea and I agree :)

**Comment by andreadelrio** [comment]
Amber's feedback: Original proposal (with slight change in text) and "Edit Profile" button to the right.
