### ISSUE TITLE
Login via Twitter breaks site

### ISSUE THREAD

**Issue by dethe** [participedia/frontend#668]
When I login using Twitter I get this on the main page: 

<img width="1261" alt="ppedia search error" src="https://user-images.githubusercontent.com/16825/32073329-82f90702-ba4a-11e7-9ad5-8eb6360959a9.png">

and a completely blank profile page:

<img width="1274" alt="ppedia blank profile" src="https://user-images.githubusercontent.com/16825/32073358-a02dfb98-ba4a-11e7-95c2-20da76720c83.png">

LinkedIn may also have problems, but I am not able to test that as I don't have a LinkedIn account.

**Comment by dethe** [comment]
This was using Firefox in Private Browsing Mode on Mac.

**Comment by jesicarson** [comment]
Removing social login for now
