### ISSUE TITLE
Ask for username as well as email when signing up

### ISSUE THREAD

**Issue by dethe** [participedia/frontend#694]
If we cannot do this via Auth0 we can strip off characters from the `@` onward and use that as the username if it is unique.

Can we, with Auth0, log in with username/password (like the existing site) or does it have to be email/password?.

**Comment by davidascher** [comment]
done.  On signup pp now asks for username + email, and people can log in with either (& their password)

**Comment by jesicarson** [comment]
@dethe @davidascher what's the status on being able to use participedia.net usernames and passwords to sign in? and will the accounts be linked to their original content on xyz when it's imported from .net? thanks!

**Comment by dethe** [comment]
Wrapping up the re-import now. Passwords won't be brought in (because we can't), but their real usernames should be tied to the content they've authored.

**Comment by jesicarson** [comment]
That's great. Just need to draft instructions for team launch... Does this make sense: "You can use your username from participedia.net to sign in, but you'll have to reset your password. Enter your username on the login screen, click 'forgot password' and follow the instructions."

**Comment by dethe** [comment]
That makes sense to me

**Comment by jesicarson** [comment]
Cool, was just wondering if that's how it will work. Or is there an easier way to prompt people to reset their passwords when they want to use their .net login for the first time on .xyz? maybe a P2 or later thing, but when we make the full switchover, many folks will likely wonder why their passwords don't work.. something to think about.
