### ISSUE TITLE
Edit sidebar of Case view

### ISSUE THREAD

**Issue by dethe** [participedia/frontend#713]
We want to show the content of the JSON we retrieve for cases. We already display the title, body, and dates. We can add `description` to the main content (second column) and the metadata from this table (https://docs.google.com/spreadsheets/d/1quhRoOrub001pVdg1TTwN4xAtEz3MOjPkWDxvuIOQsg/edit?usp=sharing) to the sidebar (first column).

Look at `src/components/CaseDetails.js` to get started. We use `intl(key)` to get localized values, where `key` is a `value_with_underscores`.

If you hit any problems or have questions, let me (@dethe) know.

**Comment by dethe** [comment]
@LLPrin has implemented round one: putting the values in the sidebar, now is working on round two: making them conditional on actually having values, organizing into groups and proper order.

**Comment by scottofletcher** [comment]
Great job you guys! Remember to get some sleep!!!
