### ISSUE TITLE
(surge form review) Edits needed for "issues" question in quick submit case form

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#715]
As per [strong drafts 1a](https://docs.google.com/document/d/1apX0QMh43rushoBEGoz_YM1HXn2rlieEX9zJwlBbeDs/edit?usp=sharing):

Please update label and instructional text to:

label:  General Issues 

Instructional Text:  Rank order up to three of the most relevant issues addressed, with “1” indicating the most relevant issue. 

@plscully According to the strong drafts, doesn't look like we're limiting to 3 choices for this question. But we are currently limiting to 3 on surge. What is correct?

Field Type: Multi-select (type to search + drop down list) / Rank order

**Comment by scottofletcher** [comment]
@jesicarson @plscully It's limited to 3 b/c it's the same field for quick submit and the full version (full version = limited to 3). Specific Topics should also be limited to 3 in both quick submit & full

**Comment by plscully** [comment]
I wrote "up to three" for all of the ranking questions intending it to also imply "no more than three". I think that's clear, but maybe we need to ask a few people if that's how they would say it? Edana, Robert, and Paolo are experts in this sort of thing if we need another opinion

**Comment by scottofletcher** [comment]
I think users will probably get it if the form won't allow them to select more than three

**Comment by jesicarson** [comment]
lol i was looking at the field type and didn't see the "up to three" in the instructional text. pls disregard :p
