### ISSUE TITLE
(surge form review) Edits needed to "Relationship" question on case form

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#726]
Label - Your relationship to this case

Values (currently the first letter of all words is capitalized, edit to the following):
I am a professional academic researcher
I am an undergraduate student researcher
I am a graduate student researcher
I was a participant
I was an organizer
I was a funder/sponsor
I helped run the process (as a facilitator, staff, etc.)
I was an observer of the process
I am a representative of a stakeholder group
I am a specialist on the issue
I am a journalist
I am an elected representative
I am a public official
I am interested in politics, but have no direct connection to this case

**Comment by dethe** [comment]
Removing the auto-formatting and auto-Title Case-ing fixed this already.
