### ISSUE TITLE
Make alphabetical search work

### ISSUE THREAD

**Issue by davidascher** [participedia/frontend#73]
I suspect this is just a bug in the api/search controller.

**Comment by davidascher** [comment]
@andreadelrio figured  out that the problem is title is an ElasticSearch *analyzed* field, which means alphabetical sort doesn't work.  Need to figure out how to maintain a parallel unanalyzed field for any field we want to sort on.

**Comment by samjiangweb** [comment]
@davidascher @andreadelrio - Also, it seems like the filter by most recent isn't working either - or at least, is not filtering by reverse-chronological order, with most recent at the top.

**Comment by davidascher** [comment]
Yes, I suspect all this is broken today.  Assigning to @dethe as he's working on the backend (which is where the bug lies I believe)

**Comment by dethe** [comment]
Fixed in the Postgres merge on the API side.
