### ISSUE TITLE
(surge form review) Edits needed to "Target Participants" values in case forms

### ISSUE THREAD

**Issue by scottofletcher** [participedia/frontend#735]
Changes needed:

"Experts (E.g. Scientists)" to "Experts (e.g. Scientists)"
"Gay/lesbian/bisexual/transgender (I.e. Lgbt) to "Gay/Lesbian/Bisexual/Transgender (i.e. LGBT)"
"People With Disabilities" to "People with Disabilities"
"Racial/ethnic Group(s)" to "Racial/Ethnic Group(s)"
"Stakeholder Organizations (E.g. Ngos, Business Interests)" to "Stakeholder Organizations (e.g. NGOs, Business Interests)"

**Comment by dethe** [comment]
This is a case where we had the right data, but had also put in an automatic formatter which screwed it up. I've removed that, and the default alphabetizing.
