### ISSUE TITLE
(surge form review) Need to be able to deselect a selection on any drop down

### ISSUE THREAD

**Issue by jesicarson** [participedia/frontend#741]
Not sure if this affects all drop downs, but on these two shown, once I've made a selection I can't deselect it in order to leave the data field empty. I tried selecting the red text, but it stays selected. Can we add an X to the red text line in the drop down once its been selected?

![screen shot 2018-02-19 at 7 22 12 pm](https://user-images.githubusercontent.com/13560530/36406243-5948ac80-15aa-11e8-9267-646005cc8508.png)

**Comment by dethe** [comment]
Adding a checkmark instead of an X because it is supported by Material-UI (and pretty standard for showing something is both selected and unselectable, it's how MacOS does it too). If needed, we can revisit for P2.
