### ISSUE TITLE
(surge form review) Edits needed to "Methods" values in case forms

### ISSUE THREAD

**Issue by scottofletcher** [participedia/frontend#745]
Not all methods in the database show up when searched. 

Eg. "Deliberation" 

.net Entry
<img width="529" alt="screenshot 2018-02-20 08 23 38" src="https://user-images.githubusercontent.com/29512491/36436049-1b491744-1618-11e8-81eb-e24b7858dd77.png">

.xyz search 
<img width="355" alt="screenshot 2018-02-20 08 24 33" src="https://user-images.githubusercontent.com/29512491/36436060-26f414a4-1618-11e8-8858-16648023fd85.png">

Eg. "Robert's Rules of Order" and "Parliamentary Procedure"

.net Entries
<img width="519" alt="screenshot 2018-02-20 08 26 49" src="https://user-images.githubusercontent.com/29512491/36436121-4f6ddbfe-1618-11e8-9eab-678b993a0e4a.png">

.xyz search 
<img width="556" alt="screenshot 2018-02-20 08 26 03" src="https://user-images.githubusercontent.com/29512491/36436138-5d31f4d2-1618-11e8-911d-d2fc528edf99.png">
<img width="418" alt="screenshot 2018-02-20 08 26 13" src="https://user-images.githubusercontent.com/29512491/36436142-6004ac86-1618-11e8-8a1d-eb4dbf9d4b57.png">

**Comment by dethe** [comment]
Fixed this in the API, it wasn't returning all results.
