### ISSUE TITLE
(surge form review) Edits needed to "Primary organizer / manager" values in case forms

### ISSUE THREAD

**Issue by scottofletcher** [participedia/frontend#750]
Not all organizations in the database show up when searched.

Eg. "92nd Street Y"
.net Entry
<img width="521" alt="screenshot 2018-02-20 13 40 09" src="https://user-images.githubusercontent.com/29512491/36450956-5893115a-1644-11e8-8b42-81a7ace1ab2a.png">
.xyz typing '9' returns no hits
<img width="390" alt="screenshot 2018-02-20 13 40 38" src="https://user-images.githubusercontent.com/29512491/36450978-62d008ee-1644-11e8-9ae8-b10e93fdf145.png">
.xzy typing 'st' returns some hits but none of them are 92nd Street Y; typing 'str' returns no hits
<img width="346" alt="screenshot 2018-02-20 13 44 29" src="https://user-images.githubusercontent.com/29512491/36451009-7ca0d15e-1644-11e8-8d52-3efcf692e631.png">

**Comment by dethe** [comment]
API was limiting lists of organizations/methods/cases to 20 due to a typo. Fixed in API.
