### ISSUE TITLE
Quick Submit Form

### ISSUE THREAD

**Issue by andreadelrio** [participedia/frontend#78]
Create quick submit form.

**Comment by andreadelrio** [comment]
@davidascher Progress for this can be found on branch [quick-submit](https://github.com/participedia/frontend/commits/quick-submit)

Front-end is almost ready, but I still need to adjust how to capture data and connect to database.

**Comment by davidascher** [comment]
Cool. I'll check out the branch.

What do you mean, 'capture' data?    Do you mean get geolocation, upload image, etc?  I'm happy to discuss all of those.  

Re: Connect to database -- we'll need to create a new API in api.js, and the right APIs in the server.

**Comment by andreadelrio** [comment]
Yes, that once the user fills a field and hits send we are storing that somewhere.
Also I saw than in EditCase you have something like mapStateToProps, mapDispatchToProps and this form doesn't have that yet. I still need to go over them to see how they work...

**Comment by andreadelrio** [comment]
Also you can find the form here [http://localhost:3000/en-US/quick-submit](http://localhost:3000/en-US/quick-submit)

**Comment by andreadelrio** [comment]
@davidascher what do I need to do to have the image upload work on my machine? Currently getting this
![image](https://cloud.githubusercontent.com/assets/4016496/20733425/26aba59c-b648-11e6-8ca2-e9a9351e3679.png)

**Comment by andreadelrio** [comment]
Depends on #80
