### ISSUE TITLE
David to figure out why upload isn't working anymore

### ISSUE THREAD

**Issue by davidascher** [participedia/frontend#80]

**Comment by andreadelrio** [comment]
@davidascher I'm getting **user doesn't have Contributors group membership**
```
OPTIONS /s3/sign?objectName=Screen_Shot_2016-10-05_at_12.41.55_PM.png&contentType=image/png 204 0.147 ms - -
user doesn't have Contributors group membership
GET /s3/sign?objectName=Screen_Shot_2016-10-05_at_12.41.55_PM.png&contentType=image/png 401 2.472 ms - 69
```

**Comment by davidascher** [comment]
Ah helpful! We.should think of a good way to communicate error messages to
the user for bug reports

**Comment by davidascher** [comment]
Should be fixed @andreadelrio

**Comment by dethe** [comment]
@andreadelrio does this work for you? I'm getting `401` on `participedia.xyz` and `Could not contact request signing server. Status = 0` on `localhost`.
