### ISSUE TITLE
Case Field 'Brief Description' is 280 characters not 140

### ISSUE THREAD

**Issue by scottofletcher** [participedia/frontend#806]
Field explanatory text and placeholder need to be updated - field now allows 280 characters to be entered (like twitter)
Explanatory text to read: Enter tweet-length (280 characters or less) description of this case
Placeholder to read: Enter tweet-length description of this case

**Comment by scottofletcher** [comment]
@dethe Can I close this?

**Comment by dethe** [comment]
I will close it when it is pushed to production. Right now the tests are failing, not because of anything we've done, but because our dependencies are out of date and the Continuous Integration tool we use for testing is choking on that. One step forward, two steps back.
