### ISSUE TITLE
Case Sidebar Data Display BUG

### ISSUE THREAD

**Issue by scottofletcher** [participedia/frontend#849]
_From @davidascher on June 18, 2018 16:40_

**Sender**: scottowenfletch@gmail.com
**Comment**: Case Sidebar Data Display BUG - only one method entered yet it appears four times in the sidebar of the reader view
[Open #207 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/207)

<a href='https://usersnappublic.s3.amazonaws.com/2018-06-18/18-40/100207da-65b7-4885-969d-9e5a23579ffb.png'>![Usersnap Feedback - Case Sidebar Data Display BUG - only one method entered yet it appears fou(...)](https://usersnappublic.s3.amazonaws.com/2018-06-18/18-40/87c139a3-6e3f-494f-a809-6877df173387.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-06-18/18-40/100207da-65b7-4885-969d-9e5a23579ffb.png'>Download original image</a>

**Browser**: Firefox 60 (Windows 10)
**Referer**: [https://participedia.xyz/case/5313](https://participedia.xyz/case/5313)
**Screen size**: 1920 x 1080 **Browser size**: 1920 x 876

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

_Copied from original issue: participedia/usersnaps#194_

**Comment by jesicarson** [comment]
closing via: https://github.com/participedia/frontend/issues/855
