### ISSUE TITLE
Severe lag when editing the narrative body

### ISSUE THREAD

**Issue by scottofletcher** [participedia/frontend#859]
There is a severe lag when typing in the editing box. I'm not a very fast typer but it's still really noticeable.
I've tried Firefox to see if that solved things (lighter browser than Chrome) but it's still just as bad. I also don't have that many tabs open and I use high speed internet.

**Comment by jesicarson** [comment]
Hey @scottofletcher I'm not seeing a lag on my machine... have you tried the all time most awesome IT support trick? aka restart your computer? lol

**Comment by scottofletcher** [comment]
haha @jesicarson yes, I did restart my computer! I also cleared my cache, browsing history (etc.) in both Chrome and Firefox

**Comment by jesicarson** [comment]
Lol well I’m stumped 🤷‍♀️
@dethe, any ideas?

**Comment by scottofletcher** [comment]
S'ok I've got a work-around: I'm now editing in .net or a Google Doc and then copy-and-pasting into xyz. Format transfers nicely (unlike .net!) as do hyperlinks :)

**Comment by ascott** [comment]
fixed with https://github.com/participedia/api/pull/354
