### ISSUE TITLE
Put Featured Cases in Fixed Order

### ISSUE THREAD

**Issue by scottofletcher** [participedia/frontend#862]
It's fine it we want to display the most recently submitted entries after the Featured Cases on the front page _but_ the Featured Cases should be in a fixed order and should not be re-ordered if one of them is edited. We should also decide if we want to have the most recently submitted or the most recently edited entries to appear after the Featured Cases - currently it's the latter but that's maybe not as useful since editors (like myself) are constantly tweaking old cases and I think visitors would be much more interested in content that's actually new.

**Comment by dethe** [comment]
Sorting by creation date instead of edited date would solve both of these, correct?

**Comment by scottofletcher** [comment]
Ideally we'd be able to specify which featured cases come first - I have a pretty good eye for what people are more likely to click on (the "boring" ones - ie. PB, Citizens Juries, etc.) but I'd still like to feature some more 'obscure' cases (global south, informal participation etc.). The click-bait should come first, the unique second

**Comment by dethe** [comment]
Being able to specify ordering, beyond sorting by date, is a completely new feature that will require changes to the database, the frontend, requires new UI, etc. We can do it, but it has to be worth the cost relative to other features.

**Comment by scottofletcher** [comment]
Ok, I don't think this is especially important (ie. definitely not P1) but we should have this function down the road - @jesicarson @plscully what do you think? If we want PPedia to be more 'timely' or 'relevant' then it's important to have the ability to feature entries on topical cases/orgs/methods. For example, if there's another sitting of the Irish Citizens' Assembly we would want to have that front and centre which would require being able to specify ordering since it's an old(er) entry

**Comment by dethe** [comment]
As we specify this feature, don't forget about localization. Right now the ordering is the same regardless of locale, but if we start picking the order, will some locales want to order things differently than others? Will some want different "featured" articles? It can get messy and we need to think that stuff through up front.

**Comment by scottofletcher** [comment]
Right, good point. I'm going to add this to tomorrow's meeting agenda, let's discuss then

**Comment by jesicarson** [comment]
Closing this. 
Soon admins will be able to feature and un-feature things. 
Decision on last call with @scottofletcher @plscully @dethe and I : Admins will only feature 4 items at one time, so no need to worry about order.
