### ISSUE TITLE
Finicky New Window External Link Icon 

### ISSUE THREAD

**Issue by scottofletcher** [participedia/frontend#869]
Clicking the little square with an arrow ![image](https://user-images.githubusercontent.com/29512491/42287310-b249653e-7f6a-11e8-94db-9e70ef3a6949.png) is very finicky - half the time it just gets selected (four squares appear in each corner like when you're resizing an image in a Word Doc)

**Comment by dethe** [comment]
Where are you seeing that? It doesn't look like a Participedia icon, is your browser sending it? Can you capture a screen grab of it?

**Comment by scottofletcher** [comment]
Oh sorry, I wasn't sure if I could screen grab it so I just copied and pasted that little icon from Google Images (turned out way larger than I wanted it to). Here's a screenshot (note that my mouse is over the link but doesn't show up in the pic): 
<img width="494" alt="screenshot 2018-07-07 14 47 26" src="https://user-images.githubusercontent.com/29512491/42414910-f52a2816-81f4-11e8-9ae7-81f19d089356.png">

**Comment by scottofletcher** [comment]
Oh, and here's what often happens when I click on it 
<img width="130" alt="screenshot 2018-07-07 14 50 27" src="https://user-images.githubusercontent.com/29512491/42414924-3f3a7f0a-81f5-11e8-9730-c11e2741ff3a.png">

Sometimes it works (opens the link in a new tab), but mostly it does that annoying selecting thing.

**Comment by scottofletcher** [comment]
1 - fantastic!! looking forward to it :)
2 - I actually like the ability to open links while editing the text because that's one of my editing jobs: checking for dead links. It would save me having to edit the entry, go to the reader view, check the urls, go back to the edit form, delete or replace those that are dead
3 - yep
4 - interesting idea - I'll defer to Jesi on how to design that

**Comment by ascott** [comment]
fixed with https://github.com/participedia/api/pull/354
