### ISSUE TITLE
Cannot Clear Formatting

### ISSUE THREAD

**Issue by scottofletcher** [participedia/frontend#871]
Cannot clear formatting or hyperlink using text editing buttons at top of narrative field. .Net was nice b/c it had a clear formatting button which would get rid of any weird fonts, links, etc. (which tends to happen when copy-and-pasting esp. if not using ctrl+shift+v)

[Open #235 in Usersnap Dashboard](https://usersnap.com/a/#/participedia-dev/p/participedia-ed971123/235)

<a href='https://usersnappublic.s3.amazonaws.com/2018-07-05/23-31/58a2ebfd-e48a-419e-ae20-f77f45403f89.png'>![Usersnap Feedback - Cannot clear formatting or hyperlink using text editing buttons at top of (...)](https://usersnappublic.s3.amazonaws.com/2018-07-05/23-31/2a65158a-5ae3-4b5e-be79-edc045d44f0e.jpg)</a>
<a href='https://usersnappublic.s3.amazonaws.com/2018-07-05/23-31/58a2ebfd-e48a-419e-ae20-f77f45403f89.png'>Download original image</a>

**Browser**: Firefox 61 (Windows 10)
**Referer**: [https://participedia.xyz/case/4538/edit](https://participedia.xyz/case/4538/edit)
**Screen size**: 2560 x 1440 **Browser size**: 2560 x 1168

Powered by [usersnap.com](https://usersnap.com/?utm_source=github_entry&utm_medium=web&utm_campaign=product)

_Copied from original issue: participedia/usersnaps#222_

**Comment by ascott** [comment]
fixed with https://github.com/participedia/api/pull/354
