### ISSUE TITLE
Profile Doesn't Show Entries Contributed

### ISSUE THREAD

**Issue by scottofletcher** [participedia/frontend#883]
![image](https://user-images.githubusercontent.com/29512491/43292946-a308df26-90ec-11e8-8fd6-8c023c9072aa.png)

These entries were submitted by Claire and go to the profile page shown above (note that text also reads "you haven't added any content yet" which should only show on my profile)
https://participedia.xyz/organization/5302
https://participedia.xyz/organization/5297

**Comment by ascott** [comment]
fixed
