### ISSUE TITLE
CSS for profile editing needs fixing

### ISSUE THREAD

**Issue by davidascher** [participedia/frontend#89]
- [x] fonts seem to big in desktop view
- [x] CSS for location picker popup needs fixing (should just look like the standard material-ui popup)
- [x] CSS for organization picker popup needs fixing (should just look like the standard material-ui popup)

**Comment by andreadelrio** [comment]
Please see PR #92

**Comment by davidascher** [comment]
The CSS for the menu is still broken for me, but I think that's covered by #94.  Closing!
