### ISSUE TITLE
Avatar menu looks odd

### ISSUE THREAD

**Issue by davidascher** [participedia/frontend#91]
the avatar is squished (since we added reactstrap, I suspect some bootstrap/material CSS conflict)
the menu has weird gradients on it

![screenshot 2016-12-11 17 56 58](https://cloud.githubusercontent.com/assets/51278/21085837/385c02c8-bfcb-11e6-88e0-a1f4f850d752.png)

**Comment by andreadelrio** [comment]
Please see PR #92
