### ISSUE TITLE
Detect when Auth0 authentication cookie is stale and logout

### ISSUE THREAD

**Issue by davidascher** [participedia/frontend#93]
Right now the UI thinks we're logged in but the token has expired AFAICT:

![screenshot 2016-12-13 15 12 11](https://cloud.githubusercontent.com/assets/51278/21163202/8154acd8-c146-11e6-94d6-625900ca8024.png)

**Comment by andreadelrio** [comment]
This issue is also affecting #80.
The picture upload doesn't work when you're logged out but UI thinks you are.

**Comment by davidascher** [comment]
fixed.
